### ISSUE TITLE
"Search for fresh Springs" quest bugged on failure 

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#100]
I failed doing the "Search for fresh SPrings" quests because npcs attacked me and made me drop the bucket but now after i came back it wont progress the quests even though i am at the spring

You are at: bx109 by116 c0 ox50.1747 oy99.2183 oz387.056 r220 (Instance 0)
![Uploading springs.PNG…]()

**Comment by echoes-emu** [comment]
Quest resets correctly ind6ab05f7
