### ISSUE TITLE
If you relog inside Thorin's Hall the the interior fails to render properly

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#101]
Loc:bx243 by250 c307 ox-3.70623 oy15.6481 oz-201.971 r246
![image](https://user-images.githubusercontent.com/96521062/153635616-97a72125-66f3-40fb-8ba9-8e3bfc1e8a91.png)

**Comment by echoes-emu** [comment]
Fixed in the next release
