### ISSUE TITLE
Captain: ''Cutting Attack''

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#103]
![image](https://user-images.githubusercontent.com/14816951/153676596-7badffff-8350-4403-a393-ed9ffd6bfa9f.png)

should be inflicting 2 dmg every 2 seconds, instead, it's only inflicting 1.
weapon used; ''Long Hatchet''

edit; only a problem at level 5 captain and below (presumably)
mob level; 5
(most likely mitigation related)

**Comment by echoes-emu** [comment]
Review, most likely caused by mitigation and rounding, damage is correct

**Comment by echoes-emu** [comment]
Confirmed, the real damage done is ~1.4 which rounds 1 in the floating combat text
