### ISSUE TITLE
Quest "Which Laid First?" fails no matter which nest you choose. Cannot Progress.

### ISSUE THREAD

**Issue by duckyhits** [echoes-emu/echoes-bt#105]
![ScreenShot00224](https://user-images.githubusercontent.com/99296795/153687908-4054a9d8-e836-467f-b5b6-43976e416ae7.jpg)

You are at: bx90 by115 c0 ox93.5978 oy69.3031 oz363.7 r32 (Instance 0) - Quest giver

Quest "Which Laid First?" fails no matter which nest you choose - Pimpinella is the correct first nest, but it fails the quest on now 2 different characters with multiple attempts. I tried the other options as well, but also fails, so it doesn't seem like an improper ordering of which next to pick.

**Comment by echoes-emu** [comment]
Fixed in 8a5ffda6
