### ISSUE TITLE
Stable Master Animation Event

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#107]
When you approach a Stable Master on foot they praise you for a fresh steed.

![image](https://user-images.githubusercontent.com/14816951/153689399-44873282-9585-4c9d-bcdd-27f8c63d3bd1.png)

**Comment by echoes-emu** [comment]
This is caused by the steed delivery quest detection not having a quest stage filter set

**Comment by bcp19** [comment]
This issue appears to have been fixed
