### ISSUE TITLE
Monsters have longer range on their melee attacks than players

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#111]
Potential minor issue with mobs/autoattack(?)
 
I've noticed while playing that the vast majority of landscape mobs have slightly higher reach than your melee skills **and your auto attack.**

![image](https://user-images.githubusercontent.com/14816951/153691683-58c93823-4b2b-4260-8023-a32d5788a3dc.png)

**Comment by echoes-emu** [comment]
This is by design. The range on player's melee is 2.5m and 3m on the gnats
