### ISSUE TITLE
Journal of Cardolan pages not removed after use

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#114]
The pages cannot be used after their first use which credits them toward the deed, so become useless and should probably be removed.
![c](https://user-images.githubusercontent.com/78056923/153695173-f7d6c843-d81c-4937-9549-df99708c59ce.png)

**Comment by echoes-emu** [comment]
Fixed in 3687b4f1, however the change required could have far reaching consequences so more quest system testing is required to confirm that everything still works as expected
