### ISSUE TITLE
Autoattack does not turn back on after Riddle

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#115]
When using riddle, autoattacks are automatically turned off (as they should be - sword sheathed in combat icon), however, subsequent attacks do not activate the autoattacks again. So if you use Riddle on one target, then switch to another target and start using offensive skills on it, autoattacks are not automatically turned on again.

**Comment by echoes-emu** [comment]
Fixed in 1b2efc4b
