### ISSUE TITLE
DPS is really low

### ISSUE THREAD

**Issue by dmorcellet** [echoes-emu/echoes-bt#117]
My champion level 5 Glumlug is equipped with what he was able to buy at Thorin's Hall.
Each fight against a blue or white mob takes forever: at least 20 skills.
His weapons are:
-an axe at 2.8DPS
- a knife (I think it's the pre-equipped one) at 0.5DPS

Is it normal? I never played SOA. The current live is really easy compared to this.

**Comment by echoes-emu** [comment]
DPS output in SOA is much lower than live
