### ISSUE TITLE
Guardian's Catch a Breath doesn't consume proc

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#121]
When getting a block proc and using catch a breath, it does not consume the proc and you can use shield swipe after it. I am pretty sure Catch a breath should consume the proc so you have to choose between.

**Comment by echoes-emu** [comment]
Seems to be a SoA-era bug in data @dawnz85

**Comment by echoes-emu** [comment]
Will be fixed in the next release (383cfb85)
