### ISSUE TITLE
Captain: Pet issues

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#123]
Just like the Lore-master pet system, they have no memory of what stance they were in when resummoned.

- Their names reset when resummoned
- They do not enter combat with you
- They do not attack upon command 
- They can't attack at all afaik, even when tested in all pet aggression modes
- Herald flag is missing
- Make Haste does not work on pet (have not tested in fellowship yet)

**Comment by echoes-emu** [comment]
Please break this down into separate issues and provide repro steps for each problem @multipunches
