### ISSUE TITLE
Champion Skill Stuck on "being Used"

### ISSUE THREAD

**Issue by Hartagil** [echoes-emu/echoes-bt#124]
the skill blade wall has a the  lit up " being used" frame while out of combat after use. this does not happen often though

**Comment by MasterTeal** [comment]
seems like it is still open.  this screen grab is after dying, believe the skill was in use when I was killed:
![image](https://user-images.githubusercontent.com/100246414/155631377-d8d97ac0-7725-42e3-a456-e61fdae1af58.png)

**Comment by echoes-emu** [comment]
Not deployed yet, please re-test in a day or two
