### ISSUE TITLE
Not waiting for friendly NPCs to finish drama can brick the instance

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#126]
Book 1, Chapter 1: Unravelling The Thread
If you continue the quest before Torthann finishes his animation he will not proceed to open the door.
[Door behind the Barrow Wight]

edit; you're able to talk to him as soon as he starts walking, (maybe only allow when he is sitting down]

![image](https://user-images.githubusercontent.com/14816951/153777687-d2c3bc92-5ae5-41e5-8527-ecf350631cc0.png)

**Comment by echoes-emu** [comment]
This particular case is fixed in a9a82015 - if more similar situations pop up, please report again
