### ISSUE TITLE
Missing workbench(s) in Thorin's Hall

### ISSUE THREAD

**Issue by duckyhits** [echoes-emu/echoes-bt#128]
![ScreenShot00238](https://user-images.githubusercontent.com/99296795/153780367-4dafe6ef-c04d-49b6-832a-d095279bb438.jpg)

You are at: bx243 by250 c307 ox114.627 oy149.289 oz-214.951 r158 (Instance 0)

2 missing workbench's in the Maker's Hall (crafting area on wing wing of the Thorin's Hall).

**Comment by echoes-emu** [comment]
Tobbex addressed these
