### ISSUE TITLE
Ability to harvest resource node's from previously had vocations remains after changing to a different vocation.

### ISSUE THREAD

**Issue by duckyhits** [echoes-emu/echoes-bt#129]
![ScreenShot00239](https://user-images.githubusercontent.com/99296795/153792309-ed5fea6d-40c2-4e07-8df0-cd3e8fe15728.jpg)

Ability to harvest resource node's from previously had vocations remains after changing to a different vocation.

example given here being a 'Historian' being able to harvest ore nodes. Not included in picture, but I can also harvest wood.

**Comment by MasterTeal** [comment]
Related item: Able to learn recipes from previous crafting vocations.

**Comment by echoes-emu** [comment]
This should be fixed now
