### ISSUE TITLE
NPC non responsive

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#130]
![NPC](https://user-images.githubusercontent.com/99280428/153870106-4fb41f07-0f46-4349-b54c-d74f37f81930.PNG)

NPC non responsive

You are at: bx119 by110 c0 ox20.6496 oy85.5128 oz457.546 r142 (Instance 0)

**Comment by echoes-emu** [comment]
Nothing irregular at that location, will need a closer look when this happens again

**Comment by echoes-emu** [comment]
Apparently this still happens, re-opening for investigation

**Comment by echoes-emu** [comment]
Fixed in data
