### ISSUE TITLE
The Hideout: Knocked down brigands appear standing up but aren't interactive

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#131]
I think these npcs are supposed to attack us when we enter the room but currently we just stand next to them for a while as sara picks up her stick and then they attack.

You are at: bx250 by153 c2 ox42.3703 oy-44.7213 oz-45.8707 r80 (Instance 4)
![more npc](https://user-images.githubusercontent.com/99280428/153882218-d8d53a4e-d509-457e-8919-193e2cfb85c8.PNG)

**Comment by echoes-emu** [comment]
The NPCs are supposed to be playing knocked down animation
