### ISSUE TITLE
Lonelands Inky/Vile Moor Webs Damage Reduction bug?

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#132]
![Capture](https://user-images.githubusercontent.com/99286164/153899209-f7c155e7-f143-4352-a1d0-04f653e0077f.JPG)
You hit the Vile Moor-web with Ballad of Resonance for 41 points of Light damage to Morale. (21)
You hit the White Hand Ridge-fighter with Ballad of Resonance for 47 points of Light damage to Morale. (20)
You hit Harmon Rushes with Ballad of Resonance for 47 points of Light damage to Morale. (20)

dealing substantially less damage than other mobs within 2 level range.
does not add up with the mitigation alignments 

Location: Inky/Vile Moor Webs at the base of Minas Eriol (lonelands)

**Comment by echoes-emu** [comment]
Nothing out of the ordinary found with these mobs. Other mobs now should have similar mitigations based on rank & level. Please re-open this if you still notice some mobs taking substantially less damage than others
