### ISSUE TITLE
Standing NPCs should return to original facing shortly after interaction

### ISSUE THREAD

**Issue by echoes-emu** [echoes-emu/echoes-bt#133]

**Comment by dawnz85** [comment]
Tested on live. Stable master at OG did not snap back after deselection, nor after running out of AOI and back, nor even after porting away, waiting a few minutes, then back. Apparently they persist this but we needn't.

**Comment by echoes-emu** [comment]
Live doesn't do this. We can add it if we feel strongly about it but for now let's just ignore it
