### ISSUE TITLE
Bog slug slime is yellow ball (Rushock Bog)

### ISSUE THREAD

**Issue by Elraen7** [echoes-emu/echoes-bt#134]
You are at: bx89 by119 c0 ox70.5622 oy153.365 oz336.753 r198 (Instance 0)
Whenever a slug does the slime, slime appears as a yellow ball.

![ScreenShot00003](https://user-images.githubusercontent.com/99693447/153956348-5ee99e45-e4e5-4748-baea-db9ce5e8c862.jpg)

**Comment by dawnz85** [comment]
duplicate of #66

**Comment by echoes-emu** [comment]
Closed the original issue but re-opening this to keep track of the /loc

**Comment by echoes-emu** [comment]
Hidden in 73f6f8bb
