### ISSUE TITLE
Quest: Wilderness by Ost Guruth - missing quest text

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#138]
The quest starts at any hunter trainer and sends you here: bx146 by116 c0 ox81.5431 oy38.4229 oz423.15 r236
The first clue is supposed to be given by the stablemaster here: bx146 by115 c0 ox35.6219 oy66.5364 oz395.133 r215 
But when talking to him you can only see the quest, but not open it for any information.
Otherwise, the quest works fine!

**Comment by echoes-emu** [comment]
Fixed in the next release (8936fe88)
