### ISSUE TITLE
Burglar trait "Blind Fury" doesn't work correctly

### ISSUE THREAD

**Issue by echoes-emu** [echoes-emu/echoes-bt#14]
Doesn't make the target prefer melee

**Comment by echoes-emu** [comment]
Very complex trait, deferring

**Comment by woodx319** [comment]
This either got fixed or was not tagged appropriately perhaps?

This trait is working fine for me. I *trick* mobs and they stop using their bows/crossbows and come into melee range for a smackdown. 

Speculating from the original wording but this trait isn't supposed to make the mob prefer melee fellow members. It pulls them out of ranged combat and into melee. 

In any case closing cuz is working fine for me in angmar :^)
