### ISSUE TITLE
Black Tide of Angmar flags permanently visible

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#143]
The flags gathered by the player for 7000176E The Black Tide of Angmar and handed in to Daervunn at bx131 by143 c0 ox143.105 oy110.03 oz422.623 r42 are permanently visible for everyone. These should not be visible until handing in the quest. Daervunn plays a drama placing each flag, then the flags should despawn an unknown time afterwards.

**Comment by echoes-emu** [comment]
Scripting added
