### ISSUE TITLE
Item [Favorite Fishing Pole] is not removed from inventory upon completing quest Mourning the Dead (Bree Land)

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#148]
As title states, after completing the quest Mourning the Dead, the [Favorite Fishing Pole] is still in inventory.

**Comment by dawnz85** [comment]
ref #114

**Comment by MasterTeal** [comment]
Quest is issued by Gail Catchpole loc:
bx121 by119 c0 ox96.0222 oy133.52 oz383.509 r227 (Instance 0)

**Comment by MasterTeal** [comment]
Same issue on quest The Errand Coinpurse issued by Lolo Wendingway at loc:
bx121 by117 c0 ox66.7326 oy124.376 oz422.988 r45 (Instance 0)

He has you go collect [Lolo's Backpack] from Neekers in midgewater marshes, looted in this approx location:
bx125 by116 c0 ox147.483 oy129.369 oz381.442 r68 (Instance 0)

After turning in the quest, the item is still in my bag.

**Comment by echoes-emu** [comment]
Seems to work fine now
