### ISSUE TITLE
Current landmark not showing up under the minimap

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#157]
The following indicators are missing when a location for an exploration deed is discovered:
1. ~~White text in the screen indicating "Discovered Hillshire Ruins" or whatever the location is.~~
2. The location text under the minimap/radar does not update to show that you have entered the location, for example changing from "Southern Bree Fields" to "Hillshire Ruins".

The deed log is updating appropriately.

**Comment by dawnz85** [comment]
The location text under the radar map is overridden by sending Landmark_DataID. Send a value of 0 when leaving the area of the Landmark to reset.

**Comment by dawnz85** [comment]
Presence or absence of billboard text is controlled by the client. It isn't shown for this deed on live either, so we have this correct.

**Comment by echoes-emu** [comment]
Will be fixed in the next release (c44d1e10)
