### ISSUE TITLE
Ranged Crit Chance Calculation Is Incorrect

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#158]
Both melee crit and ranged crit use the same calculation formula for the base value (decimal place should always be the same unless there is something that adds a non-integer modifier).  For the screenshot below (41 agility) ranged crit should be 3.5%, rather than 3.4%.

MELEE_CRIT = RANGED_CRIT = 0.536*(AGI+1)^0.5

![image](https://user-images.githubusercontent.com/100246414/156675863-e8e149a2-04e5-45b7-ab4b-85537ca70c94.png)

**Comment by echoes-emu** [comment]
That is the formula used by the server. Probably rounding done by the UI?

**Comment by MasterTeal** [comment]
That is very strange.  I have not seen a single character panel screenshot from the SoA live game where the decimal point was different between ranged and melee crit.
