### ISSUE TITLE
Volume 1 Chapter 7: Horn Call of Buckland - Craban Are Not Attackable

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#159]
Craban mobs located at:
bx106 by115 c0 ox26.7724 oy23.1364 oz341.302 r217 (Instance 0)
for quest Volume 1, Chapter 7: Horn Call of Buckland

Are not attackable.  For the quest, these fly in from above.  I used champion skill "Wild Attack" on one of them right as it was coming down, but now they are stuck with green health bars and are not attackable.  Unable to finish the quest.

After cancelling the quest to try to reset it, the quest NPCs disappeared, but I was still stuck in combat.  Unable to drop combat without logging out and back in.

![image](https://user-images.githubusercontent.com/100246414/156676417-4cf2a903-1546-491b-be5c-1c75204ed0a5.png)

**Comment by MasterTeal** [comment]
Additional info: Retried quest after cancelling.  Even without attacking Craban at all, mobs are green health bars and not attackable.

**Comment by echoes-emu** [comment]
Tried 3 times, didn't happen. Next release will have improved quest cancel logic so it should be easier to retry

**Comment by MasterTeal** [comment]
Redid this quest today, worked fine on the first try.
