### ISSUE TITLE
Captain Pet Issue

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#161]
Captain pets still do not enter combat when instructed, nor do they enter it automatically to protect you.

ironic screenshot when I tabbed out to record this issue...

![image](https://user-images.githubusercontent.com/14816951/156766882-b06d2765-82a1-4936-90dc-a970edb14736.png)

**Comment by echoes-emu** [comment]
Will be fixed in the next release (ca90d36a)
