### ISSUE TITLE
Some quest landmarks have a small radius, mobs nearby don't count toward quest completion

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#169]
Cannot complete quest "Payment in Full" in Bree Lands, issued by NPC Adso Haybank:
bx112 by119 c0 ox86.9462 oy16.7784 oz361.028 r167 (Instance 0)

Quest requires killing 8 brigands at location Old Sweetgrass Farm:
bx113 by120 c0 ox104.966 oy109.231 oz377.336 r62 (Instance 0)

These Brigands do not count towards advancing the quest.  Additionally, the location text under the radar/minimap doesn't update with this landmark.  Suspect the issue is because the landmark is not working properly, the quest probably requires brigands to be killed while in the landmark.

**Comment by echoes-emu** [comment]
Similar problem with Book 3 Chapter 2: The Gates of Fornost - landmark @ bx114 by144 c0 ox72.9273 oy88.3588 oz492.518 r253 is too small which makes the quest tedious to complete

**Comment by MasterTeal** [comment]
Now that you mention landmark area, I had issues with the landmark "Dogwood's Farm" not being large enough:
bx115 by121 c0 ox154.003 oy52.8909 oz379.345 r170

Some brigands are outside of the landmark area and don't count for the quest.  Most brigands are inside the landmark though, so I didn't have problems completing the quest.  Quest is "Thornley's Farm" issued by NPC Rose Thornley:
bx116 by123 c0 ox54.0857 oy123.584 oz389.207 r196

**Comment by echoes-emu** [comment]
Fixed in next release
