### ISSUE TITLE
Armor can be debuffed to have negative value (breaks common mit)

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#170]
When armor value is debuffed, for example from bears at:
bx121 by118 c0 ox111.366 oy20.7545 oz435.666 r87 (Instance 0)

When armor value is reduced to a negative value, common mitigation percentage does not display correctly.  See screen grab below.

I do not remember from SoA if armor value could be reduced to a negative value, or if it had a minimum of zero or one.

![image](https://user-images.githubusercontent.com/100246414/156934717-18461332-f598-454b-9069-fa363a4aeb6c.png)

**Comment by echoes-emu** [comment]
Mitigation % fixed in next release (8187d1a4)
Negative armor value in UI is rendered by the client (we don't send the final value) so we assume this part is correct
