### ISSUE TITLE
Client crash when looting

### ISSUE THREAD

**Issue by melliwuk** [echoes-emu/echoes-bt#173]
Program fault: ACCESS_VIOLATION (0xc0000005) trying to read from 0x00000000

Detailed report:

Current local time: Mon Mar 07 14:10:04 2022

Version Report generated by CoreVersion : 2.0.86 (0x02000056):
  Language: English (United States)
  CompanyName : Turbine, Inc.
  FileDescription : 
  FileVersion : 01.05.00.8110
  InternalName : lotroclient
  LegalCopyright : Copyright © 1997-2007 Turbine, Inc.
  OriginalFilename : lotroclient.exe
  ProductName : lotroclient
  ProductVersion : 01.05.00.8110 book11
  Comments : compiled Wed Oct 17 04:08:54 2007 : retail
  TurbineBuildVersion : 01.05.00.8110.retail
  TurbineType : Player External

C++ Stack Trace:
Command Line: "lotroclient_echoes.exe" -a abc -z HPhiaQpdHXg= -h 127.0.0.1:9411 --chatserver 127.0.0.1:9911 --language en_gb --rodat on --prefs "...UserPreferences.echoes.ini"
Thread ID: 17244
0x005412B1 lotroclient_echoes.exe: <unknown symbol> (params: 3b5e23b8, 2ac69090, 00001000, 00000000)
0x00541AE3 lotroclient_echoes.exe: <unknown symbol> (params: 3b5e23b8, 2ac69090, 00001000, 00000000)
0x00542D2B lotroclient_echoes.exe: <unknown symbol> (params: 2009f048, 00000001, 2a15cbec, 2ac69090)
0x00543140 lotroclient_echoes.exe: <unknown symbol> (params: 00000000, 00000000, 00000000, 00000000)

CPU register values:
  eip: 0x005412B1
  esp: 0x0019FBD0
  ebp: 0x3828F7F4
  edi: 0x00000000
  esi: 0x00000003
  ebx: 0x2A15CBEC
  edx: 0x2AC69090
  ecx: 0x00000000
  eax: 0x00000001

Raw stack
  0x0019FBB0 : 0x00000000 0x00000000 0x00000000 0x00000000
  0x0019FBC0 : 0x00000002 0x005412BC 0x3B5E23B8 0x2AC69090
  0x0019FBD0 : 0x00541AE3 0x3B5E23B8 0x2AC69090 0x00001000
  0x0019FBE0 : 0x00000000 0x00000000 0x00000001 0x2A15CBEC
  0x0019FBF0 : 0x2AC69090 0x3828F7F4 0x00001000 0x2A15CBEC
  0x0019FC00 : 0x00000004 0x00000000 0x10000E7B 0x00542D2B
  0x0019FC10 : 0x3B5E23B8 0x2AC69090 0x00001000 0x00000000
  0x0019FC20 : 0x00000001 0x2A15CBEC 0x2009F048 0x03020008
  0x0019FC30 : 0x00000000 0x00543140 0x2009F048 0x00000001
  0x0019FC40 : 0x2A15CBEC 0x2AC69090 0x005966C1 0x13BE446D

**Comment by echoes-emu** [comment]
Right click one lootable body, right click another, loot all, right click the first one, loot all

**Comment by echoes-emu** [comment]
Should be fixed in next release (04f5e4fe)
