### ISSUE TITLE
NPCs Lose Aggro When Pet Dies

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#174]
If I send a pet in to aggro things, then run in to click on quest objective, then run away... The NPCs will finish killing the pet and then reset, rather than chasing me down.  Did this on LM with raven.

Expected behavior is that when the pet dies, the mobs should come running after me.

EDIT TO ADD: If I aggro a group of mobs in this way, if I hit one of the mobs, it will come after me when the pet dies, but all the others will reset.

**Comment by echoes-emu** [comment]
Fixed in aa9f8e39
