### ISSUE TITLE
Mobs can aggro you even if you are out of sight

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#185]
For example in Minas Eriol. These mobs shouldn't be able to aggro you as you are out of sight.
bx136 by110 c0 ox73.5576 oy29.5988 oz471.15 r18
 
![image](https://user-images.githubusercontent.com/96521062/157372503-28777c06-c387-46d7-bdbe-d1ec96aafabb.png)

**Comment by echoes-emu** [comment]
Fixed in 59402504
