### ISSUE TITLE
NPC stuck in a wall

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#188]
NPC stuck in wall in lone lands Nain Enidh

You are at: bx141 by116 c0 ox138.714 oy56.6819 oz419.851 r4 (Instance 0)

![image](https://user-images.githubusercontent.com/99280428/157473201-1c27b9c7-5aca-4e39-8ee4-1d7a7ee1230d.png)

**Comment by echoes-emu** [comment]
Spawn point moved
