### ISSUE TITLE
Sometimes Unable to Purchase Skills from Class Trainer

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#195]
This has happened to me twice now, where after purchasing passive skills, then clicking the active skills tab, the "train" button is grayed out and not clickable.  Unchecking and re-checking "show only trainable skills" checkbox at the top seems to fix the issue.

![image](https://user-images.githubusercontent.com/100246414/157557978-c35e6162-4f27-44c4-ac0b-56ece077c75d.png)

**Comment by echoes-emu** [comment]
This is entirely client side so we probably can't do anything about it @dawnz85

**Comment by echoes-emu** [comment]
Client bug, nothing we can do about it at this point
