### ISSUE TITLE
Disarm effect doesn't remove weapon from hands

### ISSUE THREAD

**Issue by ghost** [echoes-emu/echoes-bt#198]
e.g. performed by Tarkrîp Raider at bx117 by135 c0 ox58.2096 oy100.629 oz421.52

**Comment by echoes-emu** [comment]
The actual disarming part of the effect seems to work so this is just cosmetic. Deferring

**Comment by woodx319** [comment]
better *loc* if anyone wants to test
You are at: bx119 by136 c0 ox16.8056 oy130.242 oz482.815 r141 (Instance 0)

I don't have live installed right now but I think on live when you got disarmed your weapons would go away and then you would like punch for very little damage. 

That doesn't happen here, you just don't attack at all. That feels SOA appropriate to me. Debuff works. you can't auto attack.
I also tested this out and got Disarmed *without* any weapons on. And you can keep punching to your heart's content while disarmed. so .. no reason but if you wanted to unequip your weapons you could punch. but the effect is only what like 5 seconds so not really worth it. Going to close feels like working fine for SOA combat
