### ISSUE TITLE
[Quest] War-master Uzorr - Orc Letter/Orders Respawn Time

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#200]
Quest War-Master Uzorr issued by Caindaith, loc:
bx136 by117 c0 ox23.7805 oy130.174 oz477.025 r239

Has you go to this location to kill War-Master Uzorr:
bx136 by120 c0 ox3.37634 oy73.529 oz500.987

Each member of the group has to loot the orc orders off the table, which take several minutes to respawn, and need to kill Uzorr each time.  Suggest that the item as a ~3-5 second respawn, and leave Uzorr respawn as-is.  This way the group can kill him once and each player can loot the orders.  Alternatively, give all players credit when one player loots the orders.

**Comment by echoes-emu** [comment]
Respawn rate fixed
