### ISSUE TITLE
Quest Items Are Not Personal Loot in Fellowship

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#202]
Example 1: Quest "An Orc Messenger"
Quest issued by Candaith: bx136 by117 c0 ox23.7805 oy130.174 oz477.025 r239
Need to kill White Hand Messenger, approx loc: bx135 by117 c0 ox90.607 oy45.9364 oz501.181 r12

If done in a group - in my case, we had 5 in the group - the first person to loot would see all 5 items Orc Orders and could loot them all, preventing the remaining four people from looting the Orc Orders.  We then went and killed it again and each person only looted one (but was able to see more).  This should be personal loot (each person can only see and loot one).

Example 2: Quest "Weavers Beneath the Ruins"
Quest issued by Hunulf Munce (Forsaken Inn): bx132 by112 c4 ox-64.5984 oy-0.712631 oz-112.869 r169
Need to kill elite spiders in the valley below Minas Eriol and loot their eyes. When done in a group, can see loot on the corpse of one eye per person in the group.  One person can loot all.  There should be personal loot one eye per person per corpse.

**Comment by echoes-emu** [comment]
Fixed in 306ca5a5
