### ISSUE TITLE
[Launcher] "Validating local content" can take a long time or even get stuck on it

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#205]
Hello, leaving this review for tarlar warlar since he does not have a github yet.

When he tries to login in he gets endless "validating content". Not sure what to do on this. Seems to happen more often since alpha 1.5 and 2. not sure there is a correlation there but figured I would mention it.

Thank you!

**Comment by echoes-emu** [comment]
New versions of the launcher should validate local content much faster after the initial check
