### ISSUE TITLE
Monster runs over gap

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#206]
bx145 by113 c0 ox35.6149 oy68.6172 oz430.271 r170

Engage the monster by the stair from across the gap. It will run across the gap to the player.
![a](https://user-images.githubusercontent.com/78056923/157590789-91697d77-006c-42d6-bacb-8aa9ca14c1af.png)

**Comment by echoes-emu** [comment]
This is correct, there's an invisible collision bridging the gap
