### ISSUE TITLE
Quest item usable through geometry

### ISSUE THREAD

**Issue by ghost** [echoes-emu/echoes-bt#218]
Chest on wooden platform usable from below and through the platform, standing at 
bx121 by136 c0 ox16.2581 oy117.618 oz477.847 r126

**Comment by Stressy23** [comment]
I won't tell you its working as intended, but this bug existed throughout SoA

**Comment by bcp19** [comment]
> I won't tell you its working as intended, but this bug existed throughout SoA

It still exists in Live to this day. There are several items you can target on the other side of a wall from them.

**Comment by woodx319** [comment]
WOA.

working as original
