### ISSUE TITLE
Wrong behaviour on looting chest for Treasures from the Fields

### ISSUE THREAD

**Issue by ghost** [echoes-emu/echoes-bt#222]
On opening the chest at bx117 by142 c0 ox111.377 oy90.7042 oz491.444 and taking the Golden Bracelet, it is possible to open the chest again and see the item. Is this correct, or should the chest become uninteractive? Check live.

**Comment by woodx319** [comment]
This feels fine for SOA. Questing is much more mindful in this era. quest Items will remain in your inventory. some quest items you can get multiple of. This feels fine for SOA quest
