### ISSUE TITLE
Drama sequence wrong on handing in The Black Tide of Angmar

### ISSUE THREAD

**Issue by ghost** [echoes-emu/echoes-bt#223]
Daervunn at bx131 by143 c0 ox141.709 oy108.635 oz422.112 r43 rushes through his drama and plays the text in the wrong sequence, putting Dol Dinen first:
![a](https://user-images.githubusercontent.com/78056923/157869353-609b233b-0022-4e59-84f6-99b53f66b577.png)

**Comment by dawnz85** [comment]
Fixed the order, so only the general problem of running in dramas remains.

**Comment by bcp19** [comment]
Note: Checked this quest and it appears to be working as intended now
