### ISSUE TITLE
Quickslot bar 5 does not seem to be avaliable

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#226]
I cannot access quickslot bar 5 even when always show is on or docked bar 5. I do not think it is there.

**Comment by bensbengittingit** [comment]
Updating this. It appears to be that both bar 4 and 5 work if you press always show bar but if you dock bar 4 or 5 they disappear.

**Comment by dawnz85** [comment]
This is a client bug preventing docking of more than three extra bars. It isn't specific to bars 4 and 5, for example if you undock 2 and 3, then 4 and 5 will dock as expected. Probably fixable.

**Comment by echoes-emu** [comment]
Client bug, closing
