### ISSUE TITLE
The Black-fire torch sometimes unusable

### ISSUE THREAD

**Issue by ghost** [echoes-emu/echoes-bt#231]
After burning at the two other locations, the torch for the south hill at bx124 by134 c0 ox114.639 oy146.396 oz437.174 r112 is not usable. Alternatively, if you do that location first, then the torch at bx125 by134 c0 ox20.9927 oy27.0808 oz452.57 r241 for the south-eastern hill becomes unusable.

**Comment by bcp19** [comment]
Collected this info on the torches in case it helps:

Selection: 0x0317B86000000133 (0x0417B86000000014)
 DID: 0x70002C98
 Loc: bx123 by134 c0 ox36.0835 oy96.0503 oz464.662 r106 (Instance 0)

me: You are at: bx123 by134 c0 ox35.4543 oy94.6466 oz464.712 r62 (Instance 0)

Selection: 0x0317D8600000017A (0x0417D86000000011)
 DID: 0x70002C97
 Loc: bx125 by134 c0 ox20.1573 oy27.624 oz452.583 r0 (Instance 0)

me: You are at: bx125 by134 c0 ox21.2479 oy26.8435 oz452.57 r217 (Instance 0)

Selection: 0x0317C860000000C0 (0x0417C8600000000C)
 DID: 0x70002C95
 Loc: bx124 by134 c0 ox117.607 oy143.598 oz437.762 r0 (Instance 0)

me: You are at: bx124 by134 c0 ox118.739 oy145.081 oz437.839 r163 (Instance 0)

**Comment by bcp19** [comment]
Used torch from north hill fire on north pile, then tried using torch from sw hill on se hill where you cannot pick up torch, but the pile wouldn't catch fire.

**Comment by echoes-emu** [comment]
Should be fixed
