### ISSUE TITLE
Black Fire Crate is rotating to face the player when interacted with

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#232]
We aren't wrongly sending a force local orientation, so the client is doing this. Find how to stop it, it's silly.

**Comment by dawnz85** [comment]
Actually, the client isn't responsible. When the player interacts with this crate, we start spamming position events for it, with a new heading based on the player position. We keep on spamming until the player leaves the area.

**Comment by echoes-emu** [comment]
Fixed in the next release (2b3b0828)
