### ISSUE TITLE
Visual artefact in the sky, Ered Luin, near Gondamon

### ISSUE THREAD

**Issue by Scoobysnacks86** [echoes-emu/echoes-bt#236]
![ScreenShot00047](https://user-images.githubusercontent.com/100969259/158032356-75b4c946-2a88-4fb9-a91f-7b643f374bc7.jpg)
bx61 by129 c0 ox38.0023 oy154.145 oz530.569 r122 (Instance 0)

**Comment by dawnz85** [comment]
Two floating braziers on top of each other in book 11 data files. Added these to the banned client entities list.
