### ISSUE TITLE
Wound effect persists after duration is over, from wolves near Gondamon

### ISSUE THREAD

**Issue by Scoobysnacks86** [echoes-emu/echoes-bt#238]
![ScreenShot00046](https://user-images.githubusercontent.com/100969259/158033299-e6046d0e-54b6-4a19-82e4-c4934b50f67d.jpg)
bx60 by128 c0 ox53.7769 oy69.6643 oz528.458 r220 (Instance 0)

**Comment by echoes-emu** [comment]
Consolidated with #302
