### ISSUE TITLE
NPCs attacking you after death

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#241]
NPCs sometimes keep hitting you after you die.

![image](https://user-images.githubusercontent.com/99280428/158043193-5b853b31-b543-419d-a9a1-f09bbb2226ea.png)

**Comment by echoes-emu** [comment]
Can't repro, needs more info

**Comment by echoes-emu** [comment]
Hasn't been reported on stress test, reopen if it happens again
