### ISSUE TITLE
Hotspots for dread pillars

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#246]
136,110: ox36.68 oy24.78 dread=2 radius=30. The remaining 3 pillars/shrines combine to cover all the area past the first pillar with 2 dread.

140,112: the two pillars on either side give 2 dread at radius 25, then the 3 dread objects in the boss area overlap to give the remainder 2 dread.

140,146: radius 30 dread 3 for all 4

125,131: the big pillar behind the bonfire gives 3 dread radius 45

97,124: 1 dread radius 10

128,122: 1 dread radius 10

**Comment by echoes-emu** [comment]
Hotspots added, if you find more please create a new ticket!
