### ISSUE TITLE
Dread hotspots

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#248]
block 109,141 offset 109,72 dread 3 radius 20
block 109,141 offset 41,88 dread 3 radius 20
block 109,140 offset 22,155 dread 3 both radius 20
others harder to determine but the general idea is: the whole fort is dread 3

60,125 - 80,33 dread 1 radius 15

146,108 - 2 altars 4 pillars all dread 3 radius 20

151,117 - all the pillars in these ruins are dread 2 radius 20

**Comment by echoes-emu** [comment]
Hotspots added
