### ISSUE TITLE
Cappy banner is not giving buffs

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#255]
not aoe buffs form captain banner

![image](https://user-images.githubusercontent.com/99280428/158434352-03684bc4-f728-41e0-9a41-bdb61d08a172.png)

**Comment by bensbengittingit** [comment]
The captain pet doesn't give buffs either

**Comment by bensbengittingit** [comment]
Make haste has the same problem

![image](https://user-images.githubusercontent.com/99280428/158437874-4301f341-3b0c-438b-9f8c-f21b319b9856.png)

**Comment by echoes-emu** [comment]
Fixed in a9de8f7c
