### ISSUE TITLE
Quest Long- Horns Bugged

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#256]
![image](https://user-images.githubusercontent.com/99280428/158435920-62e7be13-146b-41b0-b7d8-fa21b9b8612e.png)

Quest does not progress 
You are at: bx128 by141 c0 ox28.8909 oy63.5777 oz445.522 r202 (Instance 0)

**Comment by echoes-emu** [comment]
Should work already
