### ISSUE TITLE
Able to Loot and Use Items While Dead

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#258]
After dying, I am still able to loot corpses of nearby dead mobs.
Additionally, items such as map home can be used while dead (and can be interrupted with directional buttons)

**Comment by MasterTeal** [comment]
Possibly related item: mobs sometimes continue to attack while you are dead (looks like they reset, then re-aggro).  Sometimes you can still evade, etc.

**Comment by echoes-emu** [comment]
Fixed in 24611f8f
