### ISSUE TITLE
General issues about fellowship looting for quests

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#262]
Quests where you need to loot for a fellowship form a chest or cocoon etc. There is some internal cd that makes it like a 20m cd for looting stuff for other members in the fellow.

Most recent one I found was in the quest

Spider Gems 
You are at: bx130 by141 c0 ox38.3613 oy68.8731 oz413.762 r114 (Instance 0)

**Comment by echoes-emu** [comment]
already reported in #79
