### ISSUE TITLE
Skills won't go off cooldown, stuck on 7 minutes remaining

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#263]
![image](https://user-images.githubusercontent.com/96521062/159351776-470ddbbb-9f4b-446f-9ad7-c3948ea45e1c.png)

**Comment by tobbexx** [comment]
After playing for some time another skill refuse to go off cooldown.
![image](https://user-images.githubusercontent.com/96521062/159365735-0b64a593-ca16-4fd1-b656-7173b56c3bcf.png)

**Comment by Nellve** [comment]
![image](https://user-images.githubusercontent.com/101021053/159366594-2df570db-d953-4b30-93e3-08f5594a6d47.png)

**Comment by echoes-emu** [comment]
Should be fixed now
