### ISSUE TITLE
Monsters Damaged By Their Own Aura

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#265]
bx149 by116 c0 ox107.099 oy100.679 oz336.597 r73 (Instance 0)
bx150 by116 c0 ox150.643 oy59.4243 oz365.953 r157 (Instance 0)

Wight mobs are getting damaged by their own auras, and have dread from their own auras.

![image](https://user-images.githubusercontent.com/100246414/159375637-511e163b-668d-4117-af96-c13a71fa4915.png)
![image](https://user-images.githubusercontent.com/100246414/159375679-ae24829b-d6a0-4d54-9f6d-04816b379de1.png)

**Comment by echoes-emu** [comment]
Fixed in cf877bba
