### ISSUE TITLE
NPC becomes an invalid target due to hunter trap

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#266]
You are at: bx151 by114 c0 ox47.8376 oy8.56082 oz379.606 r253 (Instance 0)

![image](https://user-images.githubusercontent.com/99280428/159387559-bbe21cff-13e5-4518-aa6c-f4444269655f.png)

I trapped the boar and the trap lasted the entire duration and then the boar became invalid target and kept me in combat even after reseting

**Comment by echoes-emu** [comment]
Can't repro
