### ISSUE TITLE
Weird occurance in ND

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#268]
You are at: bx118 by138 c0 ox159.49 oy103.791 oz441.499 r201 (Instance 0)

We were at this spot in the ND where I seemed to D sync and my fellowship members could not see me moving. they just saw me standing there. It only happened to me and only in this spot. Not sure if its just my end of not but figured I would bring it up.

**Comment by echoes-emu** [comment]
Sounds like client-server traffic disruption if others were fine
