### ISSUE TITLE
Some campfires do not work

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#282]
Hunters cannot access campfires to bind themselves for the teleport

https://forums.lotro.com/forums/showthread.php?92210-Return-to-Camp-Camp-Site-Fire-locations

**Comment by echoes-emu** [comment]
e.g. Candaith encampment. Looks like this campfire might not be a milestone in book 11?

**Comment by echoes-emu** [comment]
These campsites came in later
