### ISSUE TITLE
Archet Spider mobs floating in the air

### ISSUE THREAD

**Issue by Gyniho** [echoes-emu/echoes-bt#283]
Hello,

In Archet, Sprigley's farm , couple of spider floating in the air.
![archet](https://user-images.githubusercontent.com/102246068/159748769-3c99a653-9f58-4272-bd9c-4a92463e96ec.PNG)

loc : bx123 by120 c0 ox76.4974 oy129.972 oz411.097 r176 (Instance 0)

**Comment by dawnz85** [comment]
Another example at bx165 by114 c0 ox134.638 oy6.16198 oz420.524 r106
![bear](https://user-images.githubusercontent.com/78056923/166616255-8d07eba5-be90-4c14-93f3-412145ecd0a4.png)

**Comment by echoes-emu** [comment]
Mob gravity should be vastly improved in 3f93a71a
