### ISSUE TITLE
Some loot quests progress the quest even if items don't show up in inventory

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#286]
Example:
Esteldin's Preparation. 
bx138 by142 c0 ox79.0208 oy50.6761 oz387.176 r161

Try this with full bags, loot the trove and u get 1/3 even if it doesn't show up in inventory. However, if you have them in your inventory and throw them out the quest stage changes to incomplete as it should.

Example:
Techniques Of The Masters
bx141 by144 c0 ox30.2363 oy36.5656 oz427.483 r89
Similar issue, but in this case you cannot turn in the quest even if its in a completed stage, due to book missing from your inventory. And you can't pick up the book, since the quest stage is set to finished.

**Comment by echoes-emu** [comment]
Fixed in 788df393
