### ISSUE TITLE
Quest - "Herbs and Simples" - Quest Plants Active After Completing Objective

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#287]
On quest "Herbs and Simples" at loc
bx128 by137 c0 ox36.0889 oy142.294 oz387.598 r156 (Instance 0)
this Butterbur is still glowy and looks like I can click on it after getting the ones needed for the quest but says "using that has no effect". The other ones are not clickable (eg: the one in the background of the pic).

After leaving the area to go do another quest and coming back, this plant is no longer glowy and clickable.  May be related to it being inside my draw distance when completing the objective and then moving out of draw distance and back in re-drew it?

![image](https://user-images.githubusercontent.com/100246414/160029109-ef25c10b-ef0f-46a4-9ac2-0bf1c1e44765.png)
![image](https://user-images.githubusercontent.com/100246414/160029137-4716c542-e8a2-4b9f-bd3c-7a9953873cf9.png)

**Comment by echoes-emu** [comment]
These visuals are entirely client-side, I don't think there's anything we can do about it
