### ISSUE TITLE
Instance quest resets when you die in an instance (Red Pass)

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#290]
We had a couple people die in this last npc pull and they retreated  and ran back to us. Neither of them got the quest progression and had to redo the instance and neither of their health bars showed up even though they ran back. Also we were not able to use the exit person at the end of the instance to leave the instance.

![image](https://user-images.githubusercontent.com/99280428/160264829-3cc6e97b-412e-404f-8cfc-85a817ac3e1f.png)

**Comment by tobbexx** [comment]
We(the second group) also had some issues. The biggest problem right now seems to be :
1. Dying inside and instance and going back in after retreat. You lose the instance quest progress.
2. Getting DC inside the instance. Once you relog, you spawn at Rhadagast but once u travel back in, you cant progress the instance quest.
3. 
It all boils down to 1 thing, you cannot leave and re-enter instances.

**Comment by echoes-emu** [comment]
This should be fixed now
