### ISSUE TITLE
Effects don't Persist After Logging Out and Back In

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#291]
I had dread from being defeated, logged out to the character screen and back in, and the dread was cleared.  As far as I remember, the dread should persist through the 10 minute duration, even after logging out - counting 10 minutes in real time, not 10 minutes logged into the character.

**Comment by echoes-emu** [comment]
This is not exclusive to dread, no effects persist atm

**Comment by echoes-emu** [comment]
Implemented in 73155d86
