### ISSUE TITLE
Pet vitals does not update correctly in one of the UI panels

### ISSUE THREAD

**Issue by Nellve** [echoes-emu/echoes-bt#303]
Vitals in the first image doesn't update until I click the pet.
![image](https://user-images.githubusercontent.com/101021053/161315779-35f5816c-2303-496a-b346-c732699f0704.png)
![image](https://user-images.githubusercontent.com/101021053/161315870-2c30390d-c879-42c7-9a1a-7d8de89149dd.png)

**Comment by echoes-emu** [comment]
Fixed in d914aba7
