### ISSUE TITLE
Infinite drama state

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#313]
Me and my fellow completed the quest ''The Scout Becomes The Hunter'', once I pressed finish, Amarion entered his drama state -- however, my other fellowship member pressed finish too (while armarion was performing drama), which caused him to run back and restart the drama, now he is infinitely stuck in a drama state.

I'm assuming it is an infinite drama state since when I hover my cursor over Amarion the drama icon appears.

(take a shot everytime i mention drama)

bx117 by139 c0 ox86.0684 oy133.05 oz519.05 r227

![image](https://user-images.githubusercontent.com/14816951/162291316-220e8d64-77bb-4bdc-905f-6ef0311e9dd8.png)

**Comment by tobbexx** [comment]
If both players have the turn in window open and someone press finish during drama, he gets stuck in this mode and the second player cant progress.

**Comment by echoes-emu** [comment]
Fixed in 7fa8dcd8. It should no longer be possible to turn in the quest while the NPC is performing drama

**Comment by echoes-emu** [comment]
Fixed in 7fa8dcd8. It should no longer be possible to turn in the quest while the NPC is performing drama
