### ISSUE TITLE
Crafting Jeweler Amulet Recipes Causes Server Crash

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#314]
Crafting the jeweler amulet recipes that cause alternative LM pet recipes seem to be crashing the server.

Tested the below recipes.  The third one - "Basic Amulet of the Blood Raven" - I did successfully craft 10 days ago when testing #292 - perhaps something has changed recently that has broken this?

![image](https://user-images.githubusercontent.com/100246414/162333829-ace78f92-ff48-488c-8fc4-f75f71283dc6.png)
![image](https://user-images.githubusercontent.com/100246414/162333842-ff2dfdef-1a1e-4a5e-bebc-cbce3db80f3f.png)
![image](https://user-images.githubusercontent.com/100246414/162333854-fa24bfd0-b238-4e8b-814c-3324a3aefc94.png)

**Comment by echoes-emu** [comment]
Fixed in 23dd5dff, will be deployed with the next server update
