### ISSUE TITLE
Melee Crit Passive Ranks 3 and 4 Are Not Learnable? (Champion, and perhaps others?)

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#320]
On Champion it is not possible to learn melee critical rank 3 and rank 4 passives from the class trainer.

Have high confidence that these were in the game back in SoA for champion, not 100% if they were there in book 11, but were almost certainly there by book 13-14 and there is nothing in patch notes indicating they were added.

**Comment by echoes-emu** [comment]
Seems like this is a later addition https://web.archive.org/web/20080225180738/https://www.lotro.com/article/484
