### ISSUE TITLE
Cannot Attack a great sickle fly

### ISSUE THREAD

**Issue by Hartagil** [echoes-emu/echoes-bt#321]
position : You are at: bx130 by115 c0 ox101.264 oy47.1162 oz383.613 r235 (Instance 0)
standing right ontop of the fly

error message on screen: too far away

maybe its stuck between regions (edge of midgewater marshes and lone lands)

**Comment by dawnz85** [comment]
Reproduced at that location with a Midgewater Warrior.

**Comment by echoes-emu** [comment]
Fixed in data
