### ISSUE TITLE
Monster call for help radius override not working

### ISSUE THREAD

**Issue by ghost** [echoes-emu/echoes-bt#326]
Aggroing Zaukil at bx136 by134 c0 ox129.298 oy119.484 oz474.849 r217 should aggro everyone in the tent.

**Comment by dawnz85** [comment]
He's also not starting as NPC

**Comment by echoes-emu** [comment]
Fixed, however Zaukil is setup with maximum number of "call for help" allies equal to just 4 - so he still doesn't pull the entire tent. Not sure how that should work, for now it looks like it behaves correctly based on the data though.
