### ISSUE TITLE
Characters uses wrong combat pose, causing animations to break.

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#331]
Skills that do not require use of weapons will make the character enter wrong combat pose. This breaks the first 0,5 second of the skill animation.

This pose should be used:
1. When a monster steals/disable your weapon in combat.
2. When you don't have a weapon equipped in the character tab and you enter combat.

The pose should not be used:
1. When you use skills that doesn't require a weapon.
2. When you have slotted a weapon in your character tab.

In vanilla version, the character didn't enter any combat pose at all after using skills that did not require a weapon. For example, when an LM used Burning Embers, the character used the normal idle pose before and after the skill animation. Same with mini, after a ballad is used the character returns to standard idle pose after skill animation is finished. This does not happen on Echoes.

I think this is the cause of cappy/lm res skill animations not working at all. You can see that the LM attempts to do the normal animation when resing, but it breaks as the character tries to enter this pose. 
LM:Back from the Brink
Capt:Escape from Darkness

![image](https://user-images.githubusercontent.com/96521062/164504027-8ef8bf04-b96c-4ec4-b9c0-58c5a183bcb0.png)

**Comment by echoes-emu** [comment]
Fixed in 46b45012
