### ISSUE TITLE
Fellowship Manoeuvres

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#333]
Post all FM-related issues here.

**Comment by dawnz85** [comment]
Making an incorrect yellow contribution causes the Stallion's Spirit (blue) FX to play. For example, if a red-yellow FM is attempted, the yellow contributor will get those FX.

**Comment by dawnz85** [comment]
Players will be stuck contributing if the monster dies before the FM completes.

**Comment by dawnz85** [comment]
Players contributing green or blue will try to play the contribution animation but flick to unarmed and no animation will play.

**Comment by echoes-emu** [comment]
After selecting a contribution, if you click on another color or press Esc, the client simply de-selects the target. This may be a client bug or we're supposed to close the color selection UI somehow

**Comment by dawnz85** [comment]
The oathbreaker is spawned as a signature but without signature morale bonus.

**Comment by dawnz85** [comment]
Investigate whether it should be possible to stack HoTs from different FMs.

**Comment by dawnz85** [comment]
Reports of FMs often proccing on two mobs at the same time.

**Comment by dawnz85** [comment]
Claim needing verification: using an FM skill should interrupt an induction. Tested by casting a long induction and having a fellow open an FM. Trying to contribute did send a skill exec request to the server.

**Comment by echoes-emu** [comment]
> Claim needing verification: using an FM skill should interrupt an induction. Tested by casting a long induction and having a fellow open an FM. Trying to contribute did send a skill exec request to the server.

from the wiki: _Moreover, selecting a manoeuvre does not interrupt skill induction (casting) timers, but instead your colour will not get into the manoeuvre queue until your current skill is completed._

**Comment by echoes-emu** [comment]
Seen yesterday:

- interrupting an induction when the FM goes off (by moving) then selecting a contribution gets people stuck?
- apparently changing targets should not cancel contribution? people who did this then returned to the FM target saw an empty contribution list
- some people reported seeing a different sequence than others?
- people who didn't contribute see previous contributions when the next FM pops up? (could also be the cause of the previous problem)
- some people reported seeing their re-contribution go to the old contribution's slot after canceling (again, could be related to the above issues)

**Comment by echoes-emu** [comment]
These seem to work well enough now, additional issues should be reported separately. There's also some missing feature work, for example it seems like contributions should interrupt auto-attack animations, see Trello
