### ISSUE TITLE
Select Nearest Item <Delete> Sometimes Selects [Steak Tenderizer] in Rivendell

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#337]
I have reproduced this at the following locations:
bx176 by119 c0 ox20.4562 oy34.9765 oz411.924 r136 (Instance 0) and bx176 by119 c0 ox38.5839 oy4.21485 oz411.258 r78 (Instance 0)   - Rivendell Market
bx179 by118 c0 ox3.61014 oy37.9249 oz412.967 r77 (Instance 0)    - Outside Last Homely House

Pressing the <Delete> key to select nearest item is selecting [Steak Tenderizer], but the item is not nearby.  If I /follow I will run after it but never reach the item.  Seems to be a bug of some sort.

![image](https://user-images.githubusercontent.com/100246414/165864192-d9105dbe-a007-4a1c-8d47-611cd59f8dae.png)

**Comment by echoes-emu** [comment]
afaik this functionality is entirely client-side but we'll have a look

**Comment by echoes-emu** [comment]
Should be fixed now
