### ISSUE TITLE
Captain Herald Is Attackable in Group

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#343]
While playing champion, if I move out of melee range so I will autoattack with a bow and right click on the captain's herald, I will start shooting it with bow autoattacks.  Melee skills and autoattacks do not seem to be able to hit the herald.

**Comment by MasterTeal** [comment]
Additional info, can attack captain herald with autoattacks even without retargeting, just right clicking on pet allows hitting with ranged auto attacks.

**Comment by echoes-emu** [comment]
Cannot reproduce this
