### ISSUE TITLE
When i took a ride from Rivendell to Ost Guruth my horse stopped 

### ISSUE THREAD

**Issue by Nellve** [echoes-emu/echoes-bt#348]
Loc: bx170 by111 c0 ox141.936 oy125.394 oz543.001 r0 
![ScreenShot00022](https://user-images.githubusercontent.com/101021053/166123742-78c586fa-cbcf-47d3-838e-6ff3b01d1ce2.jpg)

**Comment by tobbexx** [comment]
Horse got stuck here: bx123 by142 c0 ox75.0754 oy126.036 oz434.67 r255 
I was riding from Esteldin to Trestlebridge

**Comment by echoes-emu** [comment]
Fixed in a2f7f312
