### ISSUE TITLE
Cancelling Quest Did Not Remove Quest Item From Inventory

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#349]
On Trollshaws Quest "The Riddle Maker". 

Cancelled quest when trying to reproduce another issue.  When I later picked up the quest again, I still had the quest item in my bag and the quest went to "check mark" status, ready to turn in as soon as I picked it up.  My gut feel is that canceling the quest should remove any quest items associated with that quest from the bag, but that may have come later - canceling quests isn't super common.

**Comment by MasterTeal** [comment]
Additional info: may be an issue with this particular quest item [Besom-broom].  After turning in the quest, the quest item was not removed from inventory.

**Comment by woodx319** [comment]
merged to megga

https://github.com/echoes-emu/echoes-bt/issues/718
