### ISSUE TITLE
Can't complete quest: A Gift For The Elf-maid 

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#353]
At the stage when you are supposed to bring it back to him, he seems to be stuck on the previous stage of the quest.
Arrod: bx165 by113 c0 ox39.7548 oy49.512 oz456.418 r164
Narlinn: bx164 by115 c0 ox116.195 oy146.622 oz447.84 r144
![image](https://user-images.githubusercontent.com/96521062/166159221-f7c718a7-cef7-4464-b45f-714be441ab5b.png)

**Comment by echoes-emu** [comment]
Fixed
