### ISSUE TITLE
Horse does not dismount when entering water

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#359]
when I go into water on my horse my horse just swims and when i get out of the water I am still mounted

![image](https://user-images.githubusercontent.com/99280428/166466729-8b695d0c-3dc1-40c5-a8b7-a7f76a823759.png)

**Comment by bcp19** [comment]
This applies to the postal quests as well, entering the water while carrying mail does not fail the quest

**Comment by echoes-emu** [comment]
Fixed
