### ISSUE TITLE
Issue with quest "A Thief in the Night", cannot travel to instance.

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#36]
Its not possible to talk to the NPC to travel, nothing happens when pressing him. Loc: **breeland_oldforest_east_adsodiggerly**

**Comment by tobbexx** [comment]
If you finish the instance, you get disconnected when pressing "travel now" to leave instance.

**Comment by echoes-emu** [comment]
Fixed in e58a3963
