### ISSUE TITLE
The Iron Collar quest should not be shareable 

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#366]
This quest starts from a dropped item Heavy Iron Collar. It should not be shareable because players it is shared to won't get a copy of the collar.

**Comment by echoes-emu** [comment]
No evidence of this behavior in game data

**Comment by dawnz85** [comment]
This quest had Quest_IsShareable = False added by book 14. Prepare patch.

**Comment by echoes-emu** [comment]
Seems like this functionality came in later. The quest requires the collar for completion so sharing it doesn't seem like a big deal
