### ISSUE TITLE
Infinite Crafting Bug

### ISSUE THREAD

**Issue by fortissimo8110** [echoes-emu/echoes-bt#377]
Step 1: Select material that you can craft a high amount of and begin crafting.
Step 2: While inducting, select the item you want to craft out of thin air. (if the item requires another tool, swap tools during induction as well)
Step 3: Move to cancel crafting induction. (notice how the number in the queue will stay)
Step 4: Begin crafting the item you want to craft out of thin air. 
Note: If you have enough of one of the required materials to craft, it WILL consume those. 

https://youtu.be/3P_ukyJpxMk

**Comment by echoes-emu** [comment]
Fixed in e4ab8cbc
