### ISSUE TITLE
Relog issues

### ISSUE THREAD

**Issue by echoes-emu** [echoes-emu/echoes-bt#381]
The following sequences result in the player getting stuck at loading screen:

1. log in -> log out -> log in -> enter PE
2. log in -> enter PE -> log out -> log in

It seems like the 2nd world switch is where it breaks

**Comment by MasterTeal** [comment]
After getting stuck on the load screen when this happened, I zoned directly into the PE but did not have the instance quest.  Had to map out in order to reset.  May not be a problem once the underlying issue is addressed, but there may be other edge cases that could lead to this in the future.

**Comment by echoes-emu** [comment]
A related issue happens when entering the intro instance and then the follow-up newbie instance - the character will be rooted in place (no movement messages received from client) and content layer won't be set correctly

**Comment by echoes-emu** [comment]
Another repro (probably the same issue):
- log in a character
- log out
- log in a different character **into a different world server**
- client will get stuck on loading screen

**Comment by echoes-emu** [comment]
This _should_ be fixed in 5eb838db
