### ISSUE TITLE
Mob "Silent Moor-Stalker" Does Not Attack After First Hit

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#390]
The mob "Silent Moor-Stalker" at Drauglad in the Trollshaws (bx165 by111 c0 ox159.176 oy96.1897 oz411.604 r61) only attacks once when it comes out of stealth, after that it does not attack.

![image](https://user-images.githubusercontent.com/100246414/167274777-4bb97c88-08b8-4c8d-aac8-6a68f1b23d62.png)

**Comment by echoes-emu** [comment]
Aggregated into #136
