### ISSUE TITLE
Some Weapon Procs Do Not Work

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#391]
For example, stuns on maces, reduced evade on hammers, etc.

**Comment by MasterTeal** [comment]
I am seeing mace procs stunning so that seems to be working. hammers do put the "maim" buff on the target but doesn't show an effect on the tooltip so I'm not sure how to verify if this is working. No clear way to test swords other than testing a statistically significant quantity of hits.

**Comment by MasterTeal** [comment]
After playing with this some more, it seems like this may be working now, at least stuns on maces and the buff from hammers are proccing sometimes.

**Comment by echoes-emu** [comment]
No more problems reported with this
