### ISSUE TITLE
Book 4 Ch 8 - Cannot See Legolas Health Bar

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#401]
While doing Book 4 CH 8, cannot see Legolas' health bar as expected for an NPC being escorted next to fellowship member health bars.  Can see his health via mouseover tooltip or targeting him.

**Comment by tobbexx** [comment]
I could see his his health bar in the beginning of the instance, but after first "rest drama" the vitals bar disappeared.

**Comment by echoes-emu** [comment]
Fixed in 4510c180
