### ISSUE TITLE
NPC Guards Do Not Tag Mobs

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#403]
When NPC guards attack a mob it should tag the health bar gray and the mob should not give loot or xp.

![image](https://user-images.githubusercontent.com/100246414/167313888-bbb73274-c672-481e-a11e-cfc5e7e45356.png)

**Comment by echoes-emu** [comment]
See also #151

**Comment by echoes-emu** [comment]
Fixed in c2ec574d
