### ISSUE TITLE
[Quest] Free the Tree - Walking Tree Gets Stuck

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#415]
Doing the quest "Free the Tree" the walking tree is getting stuck at this loc:
bx92 by122 c0 ox107.002 oy158.157 oz399.069 r215 (Instance 0)

There is nothing obvious on the terrain that it is getting stuck on.  I was not able to pull it forwards by aggroing it on another mob.  I then pulled it backwards by aggroing it on another mob and after killing that it was able to progress forward past the spot it got stuck.  

EDIT to add: the spot where the tree gets stuck is right before two spiders drop down from above, perhaps it is related to that?

![image](https://user-images.githubusercontent.com/100246414/167475383-5b4040b7-f808-4ff3-b65b-1a7a76c60b1d.png)

**Comment by echoes-emu** [comment]
Fixed in 9be2b3aa
