### ISSUE TITLE
[Quest] Calling for Charcoal - Cannot Talk to Hart Holeman

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#418]
Quest has you go talk to NPC Hart Holeman, but he doesn't have a quest ring and is not interactable.

Quest Giver Hyacinth Took loc: bx94 by113 c0 ox34.8818 oy113.121 oz404.141 r130 (Instance 0)
Quest Objective Hart Holeman loc: bx95 by120 c0 ox140.68 oy61.9235 oz361.658 r246 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/167501133-05676b69-65c8-4767-9aa8-3fcaf67304d9.png)

**Comment by echoes-emu** [comment]
Fixed in data, NPC had wrong DID
