### ISSUE TITLE
[Quest] The Fate of Prunella Boffin - Incomplete Drama After Quest Turn In

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#419]
Quest Giver loc: bx100 by120 c0 ox85.7827 oy134.234 oz379.939 r255 (Instance 0)

After turning in quest, the only drama is: 
Fosco Boffin says, ''Oh, my poor Aunt Prunella! To think she'd meet her end at the hands of goblins!''

There should be a reveal that Prunella is still alive.

Seems to be a cosmetic issue only, can still advance quest without issue.

**Comment by dawnz85** [comment]
Fixed
