### ISSUE TITLE
FX will persist after effect has expired

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#42]
![image](https://user-images.githubusercontent.com/96521062/150661011-413d261a-ccf6-48bd-a791-eae3ef28348b.png)
From boards in Archet around: bx123 by122 c0 ox21.5544 oy17.6931 oz404.717 r153

**Comment by tobbexx** [comment]
![image](https://user-images.githubusercontent.com/96521062/152262496-29eeb5f4-86a8-4c6b-967a-652ecb9c882b.png)

**Comment by echoes-emu** [comment]
Can happen with toggle skills too: #92

**Comment by echoes-emu** [comment]
Could be related to #135 as well

**Comment by echoes-emu** [comment]
Should be fixed in c3693386
