### ISSUE TITLE
[RARE MOB] Naegarch spawn issue?

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#424]
You may want to investigate the spawn rate of this mob, she spawned approximately 3 minutes after being killed. 

This has happened 3 times now.

You are at: bx63 by124 c0 ox57.4641 oy80.8215 oz450.404 r152 (Instance 0)

**Comment by dawnz85** [comment]
This mob is set to spawn at the end of a series of waves. Doesn't seem to be set up to be rare unless the event itself is rare. Until we get more info, setting the event to a 1 hr respawn.
