### ISSUE TITLE
Cannot Dismount in Combat Using Horse Item

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#425]
While in combat you cannot use the horse item in bag/on skill bar to mount or dismount.  You can dismount in combat by clicking on the progressbar and clicking to dismount.  Clicking on the item in bag or skill bar should also allow you to dismount.

**Comment by dawnz85** [comment]
The client rejects the item use to dismount, not the server, therefore this is how it was at the time.
