### ISSUE TITLE
[QUEST BUG] Rescue Dora's Chickens

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#426]
If your inventory is full whilst picking up the chickens, an error prompts up saying that you do not have enough room for that item, however, the quest tracker will still increment.

Once all of the chickens have been ''collected'' the quest log updates and tells you to bring the chickens back.

... Only that you will not be able to hand the quest in because you don't _actually_ have the chickens in your backpack, despite the quest tracker saying that you have.

**Comment by MasterTeal** [comment]
Possibly related to #286 ?

**Comment by echoes-emu** [comment]
This should be fixed now
