### ISSUE TITLE
Some Mobs Name Color Is Incorrect Based on Level Difference

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#428]
In these screenshots I am level 40.  For some reason, level 42 mobs are appearing as orange to me, but they should be yellow (+2).
My understanding is:
white = +0
yellow = +1-2
orange = +3-4
red = +5-?

EDIT TO ADD: Mobs at my level and below are as expected, as are level 45 mobs. It specifically seems to be with level 42 mobs only.

![image](https://user-images.githubusercontent.com/100246414/167744038-a60a71b1-527b-45b6-8b88-85882c66a617.png)
![image](https://user-images.githubusercontent.com/100246414/167744006-c5bbed52-0e24-48ed-9f16-c16500576466.png)
![image](https://user-images.githubusercontent.com/100246414/167744020-4813553d-247e-48d0-b496-0d6572095b23.png)

**Comment by MasterTeal** [comment]
Couple of additional screenshots for reference:
![image](https://user-images.githubusercontent.com/100246414/167744434-757cde27-9345-465f-8ce0-6f55d7382b1b.png)
![image](https://user-images.githubusercontent.com/100246414/167744441-32ab78f8-9ff6-4b76-87dc-4ca54fb8b67e.png)

**Comment by MasterTeal** [comment]
Another data point: quests in my quest log are showing with the right colors.
![image](https://user-images.githubusercontent.com/100246414/167746534-f114d69c-8cf7-4432-9725-2fe88d4ae13c.png)

**Comment by dawnz85** [comment]
Client bug, under investigation

**Comment by dawnz85** [comment]
The difference from the quest colours is jarring, but this seems to be by design.
