### ISSUE TITLE
Low Level Crafting Quests

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#431]
Making one issue to capture various issues related to these.

Quest: Making Use of the Low-Lands
bx62 by130 c0 ox27.0746 oy26.0615 oz531.702 r88 (Instance 0)
Issue: After you collect the scrolls of metalworking and woodworking lore, if you consume them you can still turn in the quest.

**Comment by MasterTeal** [comment]
Zone: Shire
Quest: Camping Preparations
Loc: bx95 by120 c0 ox155.778 oy48.755 oz361.654 r198 (Instance 0)

1. collecting one campfire material and consuming/destroying it correctly brings progress back to zero. (working)
2. collecting two campfire materials will mark the quest complete. Even if you destroy or consume one or both before handing in you get credit. (not working)

**Comment by MasterTeal** [comment]
Zone: Shire
Quest: The Great Pie Crust Robbery
Loc: bx90 by113 c0 ox54.1639 oy49.6562 oz394.933 r201 (Instance 0)

Notes:
After collecting the pie crust if you delete it from your inventory or consume it in cooking, you do not lose credit towards completion of the quest and can still turn it in and get credit.

**Comment by MasterTeal** [comment]
Zone: Shire
Quest: Michel Delving's Youngest Seamstress
Loc: bx89 by113 c0 ox22.2153 oy62.7859 oz408.914 r112 (Instance 0)

Note: After collecting the tailoring lore if you delete it from your inventory or consume it, you do not lose credit towards completion of the quest and can still turn it in and get credit.

**Comment by echoes-emu** [comment]
All should be fixed now
