### ISSUE TITLE
[Quest] The Cat's Meow - Lynx Cub Odd Behavior?

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#432]
Ered Luin Quest - The Cat's Meow
In the final stage of the quest, when you coax the lynx cub out of the den, it comes out and then stands there. I can't remember if it is supposed to run back to the lodge or if you click on it to pick it up, but it seems to just stand there uninteractable but not despawning for at least several minutes. The quest updates to bring the cub back to Thrasi (and ready to turn in) which is kind of odd if the cub is still standing in front of the den.  Something doesn't seem quite right here.

Quest giver loc: bx65 by128 c0 ox127.208 oy80.9674 oz461.926 r142 (Instance 0)
Quest objective loc: bx65 by129 c0 ox115.216 oy75.6998 oz444.103 r172 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/167903536-d8d85d33-cf03-4274-80ea-ba06984816cf.png)
![image](https://user-images.githubusercontent.com/100246414/167903583-16b9b5ec-9a19-4362-b8ab-984f39fa71ab.png)
![image](https://user-images.githubusercontent.com/100246414/167903624-01eb31a6-feec-48c1-a121-bfee165e9a57.png)

**Comment by dawnz85** [comment]
The player is supposed to pick up the cub, when it will despawn and become an inventory item.

**Comment by dawnz85** [comment]
On handing in the kill-6-hendrevail stage to the den, the quest dialog flicks away after a couple of seconds. If you are fast enough to click continue, the cub will run out of the den, you'll be given the quest item, and the quest will advance. This is way off, the cub should run out, then using the cub should despawn it and give it to you as an item.

**Comment by echoes-emu** [comment]
There is nothing about using the cub in the quest description. It looks like you're supposed to just use the den and return to Thrasi. The quest dialog window seems to work correctly now, I don't see any flickering
