### ISSUE TITLE
Dread Stone Aura Affects Enemy NPCs (and May Be Wrong Level?)

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#434]
There is a dread stone at this loc:
bx138 by159 c0 ox129.528 oy49.9424 oz389.648 r11 (Instance 0)

The aura has both a dread component and a fear debuff component, both of which are applying to enemy NPCs but should only apply to player characters (and possibly pets?).

Additionally, the damage of the fear aura seems too small. If I stand in it I absorb all of the damage which seems to defeat the purpose.

![image](https://user-images.githubusercontent.com/100246414/167956718-5a846e3a-cfa5-4582-bb24-a5608cd02497.png)
![image](https://user-images.githubusercontent.com/100246414/167956689-4c5cf230-fadb-4a66-921e-72a93350361b.png)

**Comment by dawnz85** [comment]
Fixed
