### ISSUE TITLE
Champion Skill Blade Wall Should Not Enable Auto-Attack/Keep Weapons Drawn

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#435]
When using champion skill blade wall in combat:
1. If there is no target selected, or the target is selected but auto attacks are not enabled - this attack should not start auto attacks.
2. If there is a target selected and auto attacks are already enabled on that target - auto attacks should continue on that target.

If out of combat with weapons put away, using blade wall will fire the attack, then weapons should return to put away state rather than remaining in the drawn state.

If out of combat with weapons drawn before the attack - this one I'm not sure about - but my assumption is weapons would remain drawn after the attack.

**Comment by echoes-emu** [comment]
The skill is marked to enable auto-attack in the game files so this should be WAI

**Comment by MasterTeal** [comment]
I can only guess this was changed during book 12 month of the champion then. It really stands out to me as incorrect that when out of combat and using blade wall your weapons stay drawn afterwards.
