### ISSUE TITLE
Crafted Champion Rune More Than 100% Durability, Very High Repair Cost

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#446]
I crafted a Major Striking Rune to use on my champion, when I go to repair it shows that it has 100/80 durability and the repair cost seems to break when it has this level of durability.

I'm not sure how the equipped one got 100/80 durability, I tried crafting another and it has 80/80 durability.

![image](https://user-images.githubusercontent.com/100246414/168161825-53c6769e-af40-423b-a567-fae7240b2ad2.png)
![image](https://user-images.githubusercontent.com/100246414/168162685-6f686fdf-8036-4bc3-a327-fd6b0f76da75.png)

**Comment by MasterTeal** [comment]
Additional information: after logging out and logging back in, now both are 100/80

**Comment by echoes-emu** [comment]
Same for Shoes of Erebor #537

**Comment by echoes-emu** [comment]
A bunch of code was put in to try and prevent this. OG issue still unknown but this will no longer repro so I'm closing it
