### ISSUE TITLE
Mistress in the shadow quest in ram duath bugged rats

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#454]
rats in the instance where you fight the mistress of shadow attack the mistress of shadow instead of helping her.

**Comment by MasterTeal** [comment]
Additionally it seems like the Morroval inside the cave are not aggressive
bx251 by243 c29 ox-49.4979 oy75.793 oz-72.1751 r132 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/168192449-1927a6d4-2be9-4f8d-a064-3acf0df7cde1.png)

**Comment by MasterTeal** [comment]
> rats in the instance where you fight the mistress of shadow attack the mistress of shadow instead of helping her.

After attempting this quest, I'm pretty sure this is because of the bug in #89  - Morroval have an AoE skill that hits the rats, which are non-aggressive until they get hit.
