### ISSUE TITLE
Rare Mob Bullcroaker Respawn Rate

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#455]
Just killed him and he was back 2 minutes later.  By the time I finished getting this report together he had respawned again.  Drops Beryl Shards so shouldn't keep respawning at that frequency.
DID: 0x7000B702
Loc: bx164 by109 c0 ox18.5464 oy44.7075 oz342.136 r191 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/168186284-bead5146-3ff8-400e-bc5c-f174151ea0e4.png)

**Comment by MasterTeal** [comment]
Possibly related to #424

**Comment by dawnz85** [comment]
Unlike #424, this mob is controlled by a world event. We need to be able to set custom respawn period and variance.

**Comment by echoes-emu** [comment]
WorldEvents are now implemented
