### ISSUE TITLE
You cannot drop stances mid induction.

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#456]
for example, if you tried to drop war speech mid induction then it would not drop the stance until after the induction. On live you are able to drop stances mid induction. I assume it has always been a thing.

**Comment by Stressy23** [comment]
Inductions mean you are busy, when you are busy that means you are unable to use other skills. Should be WAI or at least working as SoA

**Comment by woodx319** [comment]
yeah what do you mean by 'drop' ?

Because you won't be able to do a different skill but you can always move cancel (hit 'w' to move forward a lil bit to skill cancel)
I'll test this out when i get home :D

**Comment by woodx319** [comment]
yeah this is working as intended. in SOA if you hit an induction skill you are stuck in it. easiest way to cancel it is just move. just tap _w_ or _s_ for example and cancel the induction. super easy
