### ISSUE TITLE
[Quest] Gleaning the Field - Brethilwen Falls Through Floor/Stuck in Drama

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#462]
While turning in quest "Gleaning the Field", the quest giver starts doing drama, but falls through the floor and seems to be stuck in the drama.  I have another quest to turn in to this NPC but can no longer interact because the NPC is in drama mode.

bx68 by120 c0 ox23.3384 oy125.801 oz347.116 r14 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/168294524-583bfc36-20ce-447e-8b27-b6589a376585.png)

**Comment by MasterTeal** [comment]
In case someone investigates on dev before there is a server restart, I spawned another one of him to turn in the other quest, that's why there are two.  Can't seem to despawn him.

**Comment by echoes-emu** [comment]
CNR
