### ISSUE TITLE
Floating Spawns

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#463]
Keeping a running list of floating spawns as we find them.

**Comment by MasterTeal** [comment]
Floating siege engine
bx138 by150 c0 ox60.2423 oy63.3255 oz397.852 r62 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/168404596-25566dde-6bc0-485c-91b8-d5582f089c45.png)

**Comment by MasterTeal** [comment]
Floating Corrupted Norboglir
bx144 by157 c0 ox52.7487 oy53.6258 oz352.859 r194 (Instance 0)

**Comment by MasterTeal** [comment]
Slightly floating Searing Flame-worm
bx145 by152 c0 ox53.9002 oy41.3561 oz384.028 r233 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/168441282-54f6271f-576c-4995-aecc-ddc6ef84ed99.png)

**Comment by tobbexx** [comment]
Floating slug: bx144 by157 c0 ox81.6468 oy53.8485 oz352.795 r83
![image](https://user-images.githubusercontent.com/96521062/168465524-b97176c4-7efb-4bb1-b491-8b715fd15243.png)

**Comment by MasterTeal** [comment]
^^ Tobbex's floating slug is now fixed, seems I cannot edit his post.
