### ISSUE TITLE
Logging Out While Mounted Causes Evade to be N/A After Logging In

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#464]
When I logged in and looked at my character panel, I noticed that my evade chance was N/A, but I still had parry calculating correctly.  I can reset evade to work properly by either:
1) toggling fervour on and off
2) mounting and dismounting

![image](https://user-images.githubusercontent.com/100246414/168343003-e2b1d82d-9de7-4bb3-8116-258b7d4ba65f.png)

**Comment by MasterTeal** [comment]
This seems to happen repeatably if I log out while mounted.

**Comment by echoes-emu** [comment]
Fixed in 3c4d8212
