### ISSUE TITLE
[Quest] Strength of Stone - Aggroing Siege Tower Pulls Many Many Mobs

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#465]
We aggro'd the siege tower and it didn't just pull the group of three mobs that spawned but it seemed like also two other groups of 3 from around the area, didn't see exactly where they came from.  Being a solo quest, it should only be the group of three by that siege engine.

bx138 by150 c0 ox60.2423 oy63.3255 oz397.852 r62 (Instance 0)

**Comment by MasterTeal** [comment]
Able to reproduce by attacking the orcs guarding the siege engine at this location:
bx138 by150 c0 ox55.2 oy30.21 oz397.79 r7 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/168504081-5e425344-f6f1-48fb-8960-6ac93b9958de.png)


![image](https://user-images.githubusercontent.com/100246414/168504015-7d269c06-fa27-4050-8c60-bd4c385074c4.png)

**Comment by MasterTeal** [comment]
Some further testing: It appears that ignoring the orcs and attacking the siege tower directly doesn't aggro anything.  When the siege tower is destroyed, a group of three spawns and comes after you, however, it is not the group of three that were actually guarding the tower that was just destroyed.

**Comment by echoes-emu** [comment]
Chain-pulling mobs should be fixed now. Open a new issue if there are any more problems with mobs in this area
