### ISSUE TITLE
Some entity rotations looks wrong on the server and can't be adjusted correctly.

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#47]
bx98 by120 c2 ox195.304 oy8.43872 oz-32.6855 r111
![image](https://user-images.githubusercontent.com/96521062/152868791-36d8ee73-3431-4b75-9283-54c1cf1db068.png)

**Comment by tobbexx** [comment]
bx130 by143 c0 ox81.9013 oy82.0701 oz419.065 r190
![image](https://user-images.githubusercontent.com/96521062/152868967-2918146a-8c49-4a66-a4fe-3315333196ee.png)

**Comment by tobbexx** [comment]
bx132 by143 c0 ox115.068 oy21.3782 oz429.659 r38
![image](https://user-images.githubusercontent.com/96521062/152869134-572c1c4d-e08b-4b3f-830f-22e6abf7bc05.png)

**Comment by dawnz85** [comment]
![combe](https://user-images.githubusercontent.com/78056923/153096733-9ebe5924-3419-417e-9518-b14bd4e1dc52.png)
bx121 by119 c0 ox137.803 oy97.7962 oz388.647 r219

**Comment by tobbexx** [comment]
![image](https://user-images.githubusercontent.com/96521062/154144257-dbab47d8-cb57-433a-878f-20fbc2d1343b.png)
bx132 by112 c4 ox-45.473 oy-1.36616 oz-113.756 r43

**Comment by tobbexx** [comment]
![image](https://user-images.githubusercontent.com/96521062/154144521-9973f344-002e-4301-ba32-e5bdc3a6d0c7.png)
bx132 by112 c4 ox-46.5515 oy3.43956 oz-113.756 r50

**Comment by echoes-emu** [comment]
Goldberry's bucket bx109 by116 c0 ox42.6183 oy95.7173 oz387.291 r254

**Comment by echoes-emu** [comment]
Fixed in 335c33ff
