### ISSUE TITLE
[Quest] Dark Hunters - Mob Kill Doesn't Count for Quest

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#475]
On quest "Dark Hunters", I killed a Tarkrip Warrior inside Burzum Pushdug but my quest did not increment with progress.

Quest giver loc: bx134 by155 c0 ox9.25529 oy96.4912 oz420.934 r124 (Instance 0)
Quest objective loc: bx251 by241 c47 ox-23.7685 oy-108.562 oz-83.6918 r17 (Instance 0)

![image](https://user-images.githubusercontent.com/100246414/168447132-8ca1f161-ba32-4c41-aa68-243f39902ffe.png)
![image](https://user-images.githubusercontent.com/100246414/168446838-8830f02d-cea8-42af-9081-3c0b352fd0fd.png)
![image](https://user-images.githubusercontent.com/100246414/168446834-1372d2e2-8c05-417b-b1e0-071a9be62712.png)

**Comment by dawnz85** [comment]
Missing landmark added
