### ISSUE TITLE
Stuck in combat when leaving an instance while engaged

### ISSUE THREAD

**Issue by tobbexx** [echoes-emu/echoes-bt#48]
You can currently toggle combat stance on/off by targeting a mob and clicking the auto-attack button without engaging in combat.

**Comment by tobbexx** [comment]
Getting stuck in combat happens pretty easy when running in and out of interiors with aggro.

**Comment by echoes-emu** [comment]
Entering combat should not enable auto-attack automatically

**Comment by echoes-emu** [comment]
leaving instance in combat will leave the player unable to leave combat

**Comment by echoes-emu** [comment]
Everything but the interior exit part should be fixed in 1b2efc4b
