### ISSUE TITLE
[Minstrel] Chant & Chorus of the Oathbreakers can be both active at the same time

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#481]
~~If you apply either Ire or Wrath of the Oathbreakers to a mob and run out of range, they will still stay active on the mob and do not reset - your character will also remain in a state of combat.~~

Furthermore, you can apply ''Ire of the Oathbreaker'' & ''Wrath of the Oathbreakers'' simultaneously to two different mobs.

**Comment by echoes-emu** [comment]
1. Enter War Speech
2. Cast Chorus on an enemy
3. Disable War Speech (**Chorus should deactivate and go on cooldown**)
4. Cast Chant on another enemy

- now both enemies have the toggle active

**Comment by echoes-emu** [comment]
Fixed, the toggle gets deactivate upon stance change now
