### ISSUE TITLE
Mobs Affected By Their Own Debuffs

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#488]
While doing the fire and ice instance, I noticed several of the fell spirit mobs seemed to be affected by either their own debuffs or debuffs from their allies.

![image](https://user-images.githubusercontent.com/100246414/170592519-6aa7f861-ab55-4d10-80a7-c26e6802ef87.png)
![image](https://user-images.githubusercontent.com/100246414/170592537-8956cef2-e982-4942-b844-e6dc621f77d0.png)
![image](https://user-images.githubusercontent.com/100246414/170592566-c2251b30-967b-4100-8ecd-f1a39bf3df4d.png)
![image](https://user-images.githubusercontent.com/100246414/170592585-c3adc5b9-5432-4b3c-abcf-aab3a06f1744.png)
![image](https://user-images.githubusercontent.com/100246414/170592612-84ed6796-77ef-444a-b07c-623724198edd.png)

**Comment by echoes-emu** [comment]
Probably related to #467

**Comment by echoes-emu** [comment]
Fixed in 819aec71
Please report if you see this on another mob
