### ISSUE TITLE
Target's selection does not update if the mob resets

### ISSUE THREAD

**Issue by DreadweaverLOTRO** [echoes-emu/echoes-bt#490]
Information related to your selection's target does not update after you target them. This includes the purple ring and the target's selection health bar. Unselecting and re-selecting the mob or player refreshes the targeting information. 

Expected behavior: This information should update whenever there is a change in target. 

Simple recreate: 
play burg, 
aggro a mob, 
target them, 
use hide in plain sight. 

-> the targeting information does not update and shows the mob as still targeting you despite being de-aggroed. 

![image](https://user-images.githubusercontent.com/39471882/171262907-ad2e7543-9017-4c50-aa4d-a70d7a999c60.png)

**Comment by echoes-emu** [comment]
Already fixed
