### ISSUE TITLE
Entering combat via target tooltip

### ISSUE THREAD

**Issue by LoneMartian** [echoes-emu/echoes-bt#491]
Steps to reproduce:

- Select any mob
- Right-click on it's portrait
- Hit attack

Result:
The player enters combat immediately while the mob stays out-of-combat.

Note:
This can also be achieved by using a normal right-click onto the enemy itself.

Screenshots:
![combat_via_portrait_1](https://user-images.githubusercontent.com/105127116/171269295-6b675e1d-e3ae-442f-b8cb-1ab07b62ad02.png)
![combat_via_portrait_2](https://user-images.githubusercontent.com/105127116/171269301-c60488e0-5a6e-401e-a8ec-6f5447534107.png)

**Comment by echoes-emu** [comment]
This sounds like the correct behavior? Why would the mob enter combat before you hit it? Probably need a better explanation of what the issue is
