### ISSUE TITLE
Hobbit intro instance: web-cutting sequence halts progress

### ISSUE THREAD

**Issue by LoneMartian** [echoes-emu/echoes-bt#502]
The three spiders that spawn during the web-cutting sequence in the hobbit starter instance don't always seem to be properly counted towards the quest advancement _"Defeat x/3 spiders"_. This prevents players from completing the introductory instance.

**Comment by echoes-emu** [comment]
This wasn't reported at all during the public test, might be gone? Reopen if it pops up again
