### ISSUE TITLE
Mobs don't perform auto-attack animation

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#508]
~~bx55 by129 c0 ox127.015 oy159.631 oz624.907 r249
Blue-crag Chieftain(70007F32)~~

**Comment by tobbexx** [comment]
This happens when he spawns with this weapon-type: 
![image](https://user-images.githubusercontent.com/96521062/176261236-0d7b7d26-30d5-4077-87b0-854ec14c878f.png)

**Comment by echoes-emu** [comment]
All of these are now fixed. Report any others here: #573
