### ISSUE TITLE
Combat skill queue needs improvements

### ISSUE THREAD

**Issue by echoes-emu** [echoes-emu/echoes-bt#51]
People reported being unable to get skills off while dueling, even when running on top of their target

**Comment by echoes-emu** [comment]
Entering combat always enables auto-attack, it shouldn't

**Comment by echoes-emu** [comment]
Casting a skill while out of range will immediately remove it from the queue, there should be a small delay to allow the player to move closer

**Comment by echoes-emu** [comment]
Cosmetic: 

> the skill I used as I was dying is now perma queued after retreating

**Comment by tobbexx** [comment]
Minstrel ballads should not disable auto-attacks when queued. If used at range, the delay between ballads should be about the duration of an auto-attack most likely. Reference: https://www.youtube.com/watch?v=AIuazOK1IoQ

**Comment by echoes-emu** [comment]
Improved. Additional requests/problems should be submitted separately
