### ISSUE TITLE
[Intro Quest] The Refuge Of Edhelion

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#523]
Skorgrim and his 2 Dourhands are duplicated near the end of the instance.
(They were at the bottom of the stairs before the house collapsing drama)

![image](https://user-images.githubusercontent.com/14816951/180422427-74ae13cf-e233-40a0-8b72-8dc806aede9c.png)

Loc of where they shouldn't be;
You are at: bx57 by137 c0 ox99.7813 oy118.837 oz678.109 r255 (Instance 2)

![image](https://user-images.githubusercontent.com/14816951/180422656-7958f117-5fff-4708-a7b4-13d54d4b1b75.png)

![image](https://user-images.githubusercontent.com/14816951/180422336-21bd16e9-0224-486e-a1ac-264dc82af606.png)

**Comment by echoes-emu** [comment]
This should be fixed in a8313ffb
