### ISSUE TITLE
Dying within introduction

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#524]
Dying within the introduction will teleport you to the ''real world''.    ̶(̶I̶n̶s̶t̶a̶n̶c̶e̶ ̶3̶?̶)̶ ̶-̶>̶ ̶(̶I̶n̶s̶t̶a̶n̶c̶e̶ ̶0̶?̶)̶
Relogging will spawn you back into the correct Instance.

**Comment by echoes-emu** [comment]
Fixed in 8839b652
