### ISSUE TITLE
invisible wall does not seem to be in the right place

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#528]
You cannot move out of world bounds. If you believe this is an error, please report it with the following information: bx114 by128 c0 ox158.575 oy84.9932 oz386.029 r0 (Instance 0)

**Comment by dawnz85** [comment]
Crash on teleporting to this location. Landscape looks fine so perhaps caused by the quest interior below.

**Comment by echoes-emu** [comment]
Will be fixed in the next release
