### ISSUE TITLE
Man Intro Instance - Quest Directs to Wrong Person to Leave Instance?

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#536]
_!pe 70000553:_ 
_!quest 7000002F:_ 
bx124 by124 c4 ox-1.59069 oy-16.6357 oz-18.1077 r134 (Instance 3)

Not 100% sure if this is a bug, but it certainly feels clunky...

At the very end of the Man intro instance, after defeating all the enemy NPCs, the quest log directs you to talk to Jon Brackenbrook in Archet, but he is not interactable.  In fact, you need to talk to Celandine Brandybuck to travel out of the instance, _then_ talk to Jon after you are in the normal world to complete the quest.  I'm not sure if this is just how it was, but it would be nice if talking to Jon could have you travel out, or if the quest tracker pointed you to Celandine (and then to Jon once in the normal world).

![image](https://user-images.githubusercontent.com/100246414/182052163-9c7e6d28-fa80-4e85-a862-0941e92e15de.png)
![image](https://user-images.githubusercontent.com/100246414/182052199-38a25e67-2441-4d67-846c-3bffa5778a0e.png)

**Comment by bcp19** [comment]
I think this may be working as intended as the previous dialog box has you talk to Celandine and you select finish. You then get the new objective, to talk to Jon in Archet, which happens once you again talk to Celandine and leave the instance.

**Comment by bcp19** [comment]
I just did the Book 1 Chapter 1 instance where you have to talk to Thoram to leave the instance and you see this same thing, the objective has updated to read Talk to Strider while you still have to click on Thoram to leave the instance.

**Comment by woodx319** [comment]
I think this is working as SOA as well. after you pack up eogan you talk to Mundo. He has you speak with Celandine. It then says talk to Jon in Archet. She still has the ring. Jon is wounded and emotionally devastated over on the side.
