### ISSUE TITLE
Mini Anthem buff bug?

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#543]
The two skills below when used in the same time frame over write each other with their buff. I am not sure if this is intended but they are two different skills that apply the same icmr buff but the buff name is different for each skill . I am not sure if this is WAI or a bug.

![image](https://user-images.githubusercontent.com/99280428/182514025-d1972e8c-cfa6-44af-ab28-b8247259edc0.png)

**Comment by echoes-emu** [comment]
Yes, this is WAI. The effects are not meant to stack
