### ISSUE TITLE
Equipping item issue

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#545]
If you move an item from your secondary slot to your primary slot or an item from your primary slot, the item in the that was just replaced disappears. It shows it is still in the character panel but all the effects from that item disappear and if it is a weapon then you only wield one of the 2 weapons you are shown to be holding. This applies to all pair items: weapons, earrings, bracelets, rings.

**Comment by echoes-emu** [comment]
Swapping equipped weapons no longer allowed (7b1cdb3b)
