### ISSUE TITLE
Intro Layer - Open Doors with Invisible Walls

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#547]
Playing through the elf intro. I completed the first instance, but am still in the intro layer for those quests.  There are two (visually) open doors that seem to have invisible walls and are impassable.  Either it should be passable or should appear visually as a closed door.  I cannot interact with either door ("You do not have permission to use that.").

Door locations:
bx57 by137 c0 ox80.359 oy113.556 oz678.038 r35 (Instance 2)
bx57 by137 c0 ox103.485 oy29.3905 oz687.869 r153 (Instance 2)

Also investigate gate south of Archet leading to Combe, location:
bx122 by120 c0 ox38.4223 oy86.3307 oz406.574 r149 (Instance 2)

EDIT: gate in south of Thorin's gate is good.

**Comment by echoes-emu** [comment]
Should work now
