### ISSUE TITLE
Bundle for Needlehole - Can cause server to crash

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#549]
Pick up quest "Bundle for Needlehole" > Go here and pick up item  bx92 by114 c0 ox32.4636 oy81.1034 oz363.703 r206 > get spotted by the nearest nosey hobbit to fail the quest > pick up the item again at table and run a few meters > server crashes.

**Comment by echoes-emu** [comment]
The crash seems to be unrelated to this quest
