### ISSUE TITLE
B/P/E/M is not calculated correctly in one case

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#550]
The B/P/E/M chance of low level mobs hitting a high level player is wrong. As an example, if you enter GB as a level 50 player, mobs should still be able to hit you as normal. Atm, it seems like low level mobs can barely hit you since the chanced of B/P/E/M is too high.

**Comment by echoes-emu** [comment]
Looks like it was just miss chance. Fixed in d5f4d866

Resist and mitigation are still modified by level difference, maybe something to look into as well
