### ISSUE TITLE
Quest Bug: The Wisdom of the Thrushes

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#56]
Quest: The Wisdom of the Thrushes
Bug location: at defend Nos Grimsong from x2 Lynxes
Bugs how: The Lynxes do not enter combat and thus you cannot defend him.
Bug Co-ordinates : bx54 by133 c0 ox68.7048 oy114.728 oz581.948 r67 (Instance 0)

More Info : Deleted the quest, tried again, bugged again at the same point.
![Capture](https://user-images.githubusercontent.com/99286164/153092516-8288c475-6523-4495-9b91-68cde8d24bd5.JPG)

**Comment by echoes-emu** [comment]
Fixed
