### ISSUE TITLE
Chatserver issues

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#563]
If you get disconnected from the game, or a client crash for example. The fellowship/regional and custom channels stops working. You can't see any messages in these channels. Only /tell works. Restarting the game won't solve the issue, it only works after server restart.

**Comment by echoes-emu** [comment]
This _should_ be fixed in 61fa6591

**Comment by echoes-emu** [comment]
Closing now, report individual issues separately if they occur again
