### ISSUE TITLE
Carn Dum: Hanging merrevail do not descend to the ground

### ISSUE THREAD

**Issue by LoneMartian** [echoes-emu/echoes-bt#568]
![image](https://user-images.githubusercontent.com/105127116/200128633-d996475d-a825-4353-b2a6-281130e72fe6.png)

/loc: `bx140 by172 c0 ox51.9938 oy89.4972 oz687.507 r141`

**Comment by woodx319** [comment]
merged with https://github.com/echoes-emu/echoes-bt/issues/336
