### ISSUE TITLE
Silverdeep Mine Door Missing (cannot exit)

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#58]
Bug: Cannot exit Silverdeep Mine (Thorins Hall Eastern Mine)
Location: bx247 by252 c2 ox27.3108 oy43.4956 oz-106.931 r89 (Instance 0)

![Capture](https://user-images.githubusercontent.com/99286164/153092671-86d011de-0cd7-44ab-917f-4b8a623d030f.JPG)

**Comment by echoes-emu** [comment]
Fixed
