### ISSUE TITLE
LM ability Lightning Strike is broken

### ISSUE THREAD

**Issue by Gingerbreadfriend** [echoes-emu/echoes-bt#586]
The ability will channel and a lightning effect will appear on your own character but no damage will be dealt to the enemy with no lightning effect on them.

**Comment by echoes-emu** [comment]
This is likely about Lightning Storm, which only hits targets affected by Ancient Craft, as per the tooltip

**Comment by dawnz85** [comment]
If you use Lighting Storm with no valid target (e.g. a target without Ancient Craft), the skill plays and goes on cooldown anyway. I'm pretty sure this is not how it worked. Will look for a suitable error message.

**Comment by dawnz85** [comment]
Suggest Skill_TargetEffectReqsNotMet

**Comment by echoes-emu** [comment]
Fixed in 9f18df35

The induction still plays because AoE targets are only checked after induction finishes. But the skill no longer goes on cooldown at least
