### ISSUE TITLE
Area causing server crash

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#59]
Once you enter ''The crumbled Court'' it will cause the server to crash.

Imperative area for the deed ''The History of the Dúnedain'' - (contains the ''Ancient inscription'')  & the quest ''The Errant Coinpurse''

bx121 by117 c0 ox153.279 oy85.8672 oz428.863 r52

**Comment by dawnz85** [comment]
Crash also occurs without either of the mentioned deed or quest in progress.

**Comment by echoes-emu** [comment]
Fixed
