### ISSUE TITLE
Pigs might fly

### ISSUE THREAD

**Issue by ghost** [echoes-emu/echoes-bt#591]
This pig just walked straight up the side of a house. To my distress, I was unable to follow him. Clearly we need to allow players to walk up the sides of buildings too. 
bx117 by118 c0 ox84.6502 oy75.3802 oz391.268 r126
![a](https://user-images.githubusercontent.com/78056923/205162346-370c2f5d-b1ad-4213-b8e6-7ab9dff3bdaf.png)

**Comment by woodx319** [comment]
Merging _ Mobs or Objects offset from their correct position / altitude #934 _
