### ISSUE TITLE
Players still falling through terrain

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#594]
Happens for some at:
Exiting Combe crafting hall. Lands here:bx122   by119 c0 ox119.052 oy85.0154 oz406.558 r71
Exiting Combe Cartwells House 
Exiting Combe Training Hall
Brockenborings office
Map to Bree - Landed here: bx131 by112 c0 ox113.268 oy22.1355 oz434.302 r28
Entering Archet Jail Landed here: bx122 by124 c4 ox115.543 oy51.1745 oz405.085 r0 (Instance 4)
Thorin's Hall milestone. Landed here: bx243 c384 ox-1.85547 oy47.6875 oz-200.071 r87
Exiting Prancing Pony(seems to be very common)
Fell under the stairs when I left the room.(bx122 by119 c0 ox119.957 oy85.9987 oz403.941 r193)

**Comment by echoes-emu** [comment]
Some fixes were deployed and haven't heard about this since. Please reopen if it still happens
