### ISSUE TITLE
Night/day-time genrators doesn't work reliably

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#611]
The ghost in the bree alley does not appear. Loc: bx119 by115 c0 ox111.116 oy108.122 oz390.92 r48 (Instance 0)
Shadow of the white hand. Spy does not spawn at evening or midnight times \nYou are at: bx118 by120 c0 ox15.4928 oy75.726 oz398.28 r211 (Instance 0)
Bill Ferny does not spawn at evening or midnight times

**Comment by echoes-emu** [comment]
This should be fixed now
