### ISSUE TITLE
Instance: The Refuge of Edhelion can break sometimes

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#630]
he introduction instance for elves is bugged. When I get to the gate to follow Dorongur the gate doesnt open and the NPCs just stand there. Can be caused by mobs respawning? Or taking too long time to get to the gate that is supposed to be open by the elves.

**Comment by echoes-emu** [comment]
The problem _seems_ to be a respawning generator. I turned off the respawning, let's see if that fixes it
