### ISSUE TITLE
Sometimes when zoning into Archet Jail you end up here. bx122 by124 c4 ox102.083 oy52.1372 oz404.586 r176

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#640]

**Comment by dawnz85** [comment]
This position is close to the landscape entrance. No coordinate is close to the interior entrance. Cell 4 is the correct entrance cell, so placement failed somehow?

**Comment by echoes-emu** [comment]
Tentatively closing this, there are some new changes that should prevent this. Reopen if it's still happening
