### ISSUE TITLE
Pets sometimes disappear 

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#649]
Every 5mins or so while farming wargs at Annundir for sturdy hide, my bear is vanishing. It is invisible, not stuck or dead. It will be fighting then vanish into thin air. not seen it outside of this area.

**Comment by dawnz85** [comment]
Try to find out what can make the bear reappear: does it reappear sporadically, does it need to be resummoned, does the player need to relog?

**Comment by dawnz85** [comment]
What happens if the player casts a heal on the bear when it's invisible? Is it out of range? (Falling through terrain.) Contact the player and visit them, targeting the bear and getting info and loc when it disappears.

**Comment by echoes-emu** [comment]
Probably the same problem as here: #794
