### ISSUE TITLE
 Duillond reflecting pool graphic(?) issue

### ISSUE THREAD

**Issue by duckyhits** [echoes-emu/echoes-bt#66]
![ScreenShot00027](https://user-images.githubusercontent.com/99296795/153119354-dbb6c1bb-91f9-403a-8a47-aaf63397c3ce.jpg)

You are at: bx67 by125 c0 ox5.50643 oy93.2109 oz488.77 r220 (Instance 0)

Duillond reflecting pool!!

**Comment by dawnz85** [comment]
Also happening with dying slugs in Rushock Bog e.g. bx89 by119 c0 ox70.5622 oy153.365 oz336.753 r198

**Comment by echoes-emu** [comment]
Fixed in data
