### ISSUE TITLE
AOE attacks do not work on adds that are summoned by an enemy mob if not targeted

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#667]

**Comment by Stressy23** [comment]
Aoes do not hit wolves in the GA instance either

**Comment by Stressy23** [comment]
Various associated Monsters for these books have issues, but the quests themselves are working properly.
Foul wrigglers spawned by Ancient Bile-Spewers are non-hostile on spawn
image

Selection: 0x0319774000000245
DID: 0x70007BDC
Loc: bx151 by116 c0 ox3.59832 oy126.739 oz370.147 r122 (Instance 0)
Move table: 0x0700012C
State stack:
(Patrol) default patrol @ 0.5x
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

image

Selection: 0x0319674000000060
DID: 0x700072E0
Loc: bx150 by116 c0 ox30.8543 oy64.4516 oz334.506 r71 (Instance 0)
Move table: 0x0700058C
State stack:
(Idle - pet)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

image

Selection: 0x03197740000003AA
DID: 0x70000CDA
Loc: bx151 by116 c0 ox91.339 oy85.3537 oz397.83 r192 (Instance 0)
Move table: 0x0700012C
Cosmetic loadout: 0x70000CE3
melee: hatchet
State stack:
(Idle - pet)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

Summoned wights from
image

Selection: 0x0319774000000396 (0x041977400000003E)
DID: 0x70000690
Loc: bx151 by116 c0 ox146.246 oy68.7224 oz416.477 r192 (Instance 0)
Move table: 0x07000125
Cosmetic loadout: 0x70000CD7
melee: Stave
State stack:
(Idle)
Melee combat mode: combat_2h
Ranged combat mode: combat_monster
KungFu NPC: No

Are unable to be attacked with damaging aoes. Non-damaging ones such as ancient craft Do hit the target
From the same mob
image

Selection: 0x03197740000003B0
DID: 0x70000801
Loc: bx151 by116 c0 ox146.246 oy68.7224 oz416.477 r173 (Instance 0)
Move table: 0x0700012C
State stack:
(Idle - pet)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No
Mob spawns as aggressive but is not linked to summoner. A level 50 character will not trigger its aggro. Also not hit by Aoes

Lone Lands quests that are working
The Stone-Speaker
To Agamaur
Tainted Living
Fallen Oak
Rhudaurs Traitors
Proofs Burden
Dead Water
Angmars Dead
Cutting of the hand
Long overdue Justice

Adding more

**Comment by echoes-emu** [comment]
Should be fixed now
