### ISSUE TITLE
Quest Items in Fellowships

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#67]
![image](https://user-images.githubusercontent.com/14816951/153119554-2a2b25cd-9fbb-4079-bfcb-6b9412f432fb.png)

![image](https://user-images.githubusercontent.com/14816951/153119741-5c617ffe-10e4-4d79-b7da-7ce11f252ed1.png)

The example used above is ''Poscos Uncle''

I'm assuming because I killed the mob that drops the quest item in a fellowship, it decided to give 2 of that particular item as opposed to sharing it both between us.

**Comment by multipunches** [comment]
![image](https://user-images.githubusercontent.com/14816951/153125313-e261a9ba-20e4-436f-8e1d-f7d7868ec182.png)


further evidence that it may be dependent upon how many people are in your fellowship^
[3 rurik receipt]

**Comment by echoes-emu** [comment]
Fixed in 5232b42f
