### ISSUE TITLE
Platinum does not spawn in the trollshaws 

### ISSUE THREAD

**Issue by Stressy23** [echoes-emu/echoes-bt#690]
Checked the entire trollshaws and saw no platinum spawning. All "precious" Nodes were Gold ore instead. Can find Platinum in the Ram Duath so it is still in game
![image](https://user-images.githubusercontent.com/122374802/211693777-535aaf9a-e2fc-4587-a91f-5a50c4209f46.png)
You are at: bx173 by113 c0 ox135.522 oy151.297 oz705.514 r123 (Instance 0)

**Comment by echoes-emu** [comment]
WAI. resource spawns come from a 100% reliable source
