### ISSUE TITLE
Skorgrim sometimes gets stuck in epic prologue

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#696]
In the Elven epic prologue when you get to the final fight Skorgrim will sometimes bug.
You are at: bx60 by125 c0 ox96.5904 oy47.788 oz483.795 r190 (Instance 2)
![image](https://user-images.githubusercontent.com/122328856/211864420-264deb14-7d38-4444-8a52-89e33609c6f1.png)

**Comment by bcp19** [comment]
He got stuck again today.
Quest Instance:
Assault on Rath Teraig

Quest Giver: 
Langlas
Selection: 0x03141800000002C1 (0x0414180000000007)
 DID: 0x70000669
 Loc: bx65 by128 c0 ox131.168 oy74.9711 oz462.319 r27 (Instance 0)
 Move table: 0x0700003B
State stack:
(Interacting)
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

Skorgrim:
Selection: 0x0313C7D002000061 (0x0413C7D000000020)
 DID: 0x7000726C
 Loc: bx60 by125 c0 ox94.9141 oy48.1458 oz483.971 r133 (Instance 2)
 Move table: 0x070001E7
State stack:
(Patrol) SkorgrimIn @ 0.25x
(Drama) signal_enterworld
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
Drama: signal_enterworld

**Comment by menthur** [comment]
can confirm. just happened to my aswell.

info:
Selection: 0x0313C7D005000061 (0x0413C7D000000020)
 DID: 0x7000726C
 Loc: bx60 by125 c0 ox94.9276 oy48.2779 oz483.995 r133 (Instance 5)
 Move table: 0x070001E7
State stack:
(Patrol) SkorgrimIn @ 0.25x
(Drama) signal_enterworld
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
Drama: signal_enterworld

loc:
You are at: bx60 by125 c0 ox102.612 oy39.2384 oz482.096 r216 (Instance 5)

![ScreenShot00031](https://user-images.githubusercontent.com/122735660/213310479-2534a139-4549-4976-9646-732990cca969.jpg)

**Comment by woodx319** [comment]
lolol never even noticed him must have gotten stuck for me as well. Going to merge

**Comment by woodx319** [comment]
https://github.com/echoes-emu/echoes-bt/issues/433
