### ISSUE TITLE
General Error if attempting to loot a corpse while another loot window is opened

### ISSUE THREAD

**Issue by Gilnaure** [echoes-emu/echoes-bt#704]
Steps:
1. Kill a few mobs near each other.
2. Try to loot the first corpse - the Items window will open.
3. Don't take anything and try to loot another corpse.

![ScreenShot00049](https://user-images.githubusercontent.com/122461442/211931746-af03fc74-c7db-4c6a-bae8-ce3a63304746.jpg)

**Comment by echoes-emu** [comment]
Working as intended, this is a workaround for a client crash

**Comment by TurdFerguson79** [comment]
Sad to hear, but definitely worth the annoyance if it means a functioning game.  It would probably be near the top of most QoL improvement lists if at some point in the future there's an alternate workaround.  Those poor, poor Champs
