### ISSUE TITLE
Quest Searching for Fresh Springs is not advancing

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#706]
I picked up the quest Searching for Fresh Springs from Adso's Camp and headed to Goldberry's Spring and Goldberry would not activate. I thought it may be because I had invis active so I turned it off, still would not activate, Cancelled quest waited 5 min and picked it up again and stayed off invis and still would not activate. Character had previously found Goldberry's spring before taking quest, would this possibly be the cause of the problem?

**Comment by woodx319** [comment]
what do you mean by previously found the spring? Did you get to that point and canceled the quest or what?

**Comment by echoes-emu** [comment]
Possibly related to discovering landmarks before their deed/quest

**Comment by bcp19** [comment]
The Breeland Deed for the Old Forest. I had been through that area before getting the quest, so had 'discovered' the spring before getting the quest. The quest objective "find the spring" would never update to talk to Goldberry

**Comment by echoes-emu** [comment]
Should be fixed, see #711
