### ISSUE TITLE
Sign of the Wild: Protection (Lore-Master) skill (seemingly) stacks rather then refreshing; does not actually apply stats beyond 1.

### ISSUE THREAD

**Issue by duckyhits** [echoes-emu/echoes-bt#71]
![ScreenShot00035](https://user-images.githubusercontent.com/99296795/153127520-bd3699c8-9f5a-447d-8483-181bafd4f913.jpg)

universal location

Can stack continuously - 5 minute duration with a 30(?) second cool down, but does not effect stats beyond the first.

**Comment by echoes-emu** [comment]
Fixed in 5c960346
