### ISSUE TITLE
Already discovered landmarks in Introduction won't contribute to deed after Intro

### ISSUE THREAD

**Issue by Brystan** [echoes-emu/echoes-bt#711]
Ran a char through archet intro, didn't get discovery deed during intro (probably should)
Then when running char after intro, deed only got appeared after going to Blackwold HQ. Going back to Bronwe's Folly or Blackwold's Roost doesn't advance them on the deed.

**Comment by TurdFerguson79** [comment]
I had and reported that same issue on open beta, figured it was just me.  Was maybe my 4th or 5th character I took through that intro too, which seemed odd, because the others didn't have a problem with the deed

**Comment by MasterTeal** [comment]
See #685

**Comment by echoes-emu** [comment]
Should be fixed now, please re-test
