### ISSUE TITLE
Megathread: mobs that do not attack and cannot be attacked

### ISSUE THREAD

**Issue by SpinexLive** [echoes-emu/echoes-bt#716]
Goblin in Nan Wathren

16.2S, 47.6W
![image](https://user-images.githubusercontent.com/74355368/212123359-82c5b8f9-d310-4070-b1a3-89ea681fe40a.png)

One goblin cannot be attacked and does not attack.

**Comment by bcp19** [comment]
Sturdy Long Tusk "swiimming"

You are at: bx152 by113 c0 ox93.7257 oy117.96 oz347.433 r29 (Instance 0)

**Comment by bcp19** [comment]
Not a mob, but a pathing NPC issue: Labourer cannot walk up the stairs

Selection: 0x031F3FA000000477 (0x041F3FA0000000D3)
 DID: 0x70006FBF
 Loc: bx243 by250 c289 ox-5.60824 oy84.3089 oz-199.564 r129 (Instance 0)
 Move table: 0x070001E7
State stack:
(Patrol) default patrol @ 0.5x
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

You are at: bx243 by250 c384 ox-1.98379 oy84.2057 oz-199.616 r196 (Instance 0)

**Comment by bcp19** [comment]
Goblin in Vale of Thrain:

Selection: 0x0313882000000080
 DID: 0x70007F28
 Loc: bx56 by130 c0 ox49.1375 oy109.665 oz520.669 r32 (Instance 0)
 Move table: 0x0700018E
 Cosmetic loadout: 0x700017CF
   melee: Mace
State stack:
(Wander)
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by menthur** [comment]
spawned close to the goblin fortress in Noglond. Mob is not attackable, and does not attack.

location:
You are at: bx56 by130 c0 ox52.3507 oy112.321 oz548.584 r182 (Instance 0)

mob:
Selection: 0x0313882000000026
 DID: 0x70007F28
 Loc: bx56 by130 c0 ox49.1375 oy109.665 oz520.669 r32 (Instance 0)
 Move table: 0x0700018E
 Cosmetic loadout: 0x700017CF
   melee: Mace
State stack:
(Wander)
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: No
![ScreenShot00025](https://user-images.githubusercontent.com/122735660/213018326-ddede8d3-b0c0-4ebc-a048-f291f0a057e9.jpg)

**Comment by bcp19** [comment]
Putting these here as they are green mobs (plus one is underground)

Morroval:
Selection: 0x03197A600000006B (0x04197A6000000017)
 DID: 0x70008652
 Loc: bx151 by166 c0 ox57.5091 oy125.428 oz386.382 r0 (Instance 0)
 Move table: 0x07000362
 Cosmetic loadout: 0x70008658
   melee: dagger
State stack:
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: Yes

Selection: 0x03197A600000006A (0x04197A6000000016)
 DID: 0x7000864E
 Loc: bx151 by166 c0 ox56.8768 oy126.725 oz386.19 r0 (Instance 0)
 Move table: 0x07000362
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: Yes

Wild Bloodfang (underground)
Selection: 0x03197A600000006C (0x04197A6000000019)
 DID: 0x70002D5E
 Loc: bx151 by166 c0 ox58.5956 oy124.425 oz386.476 r0 (Instance 0)
 Move table: 0x07000374
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by bcp19** [comment]
More found, think they may be for a quest involving this NPC and not supposed to be visible yet: (Don't yet have the quest)

NPC:
Muiladan
Selection: 0x03197A6000000070 (0x04197A600000001D)
 DID: 0x70008652
 Loc: bx151 by166 c0 ox28.9801 oy96.9852 oz390.342 r17 (Instance 0)
 Move table: 0x07000362
 Cosmetic loadout: 0x70008655
   melee: dagger
State stack:
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: Yes

Moroval
Selection: 0x03197A6000000070 (0x04197A600000001D)
 DID: 0x70008652
 Loc: bx151 by166 c0 ox28.9801 oy96.9852 oz390.342 r17 (Instance 0)
 Move table: 0x07000362
 Cosmetic loadout: 0x70008655
   melee: dagger
State stack:
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by bcp19** [comment]
More still:

Morroval
Selection: 0x03195A7000000027 (0x04195A7000000006)
 DID: 0x70008652
 Loc: bx149 by167 c0 ox50.8929 oy116.65 oz445.541 r221 (Instance 0)
 Move table: 0x07000362
 Cosmetic loadout: 0x70008654
   melee: dagger
State stack:
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: Yes

Selection: 0x03195A7000000028 (0x04195A7000000005)
 DID: 0x70008652
 Loc: bx149 by167 c0 ox51.0319 oy117.845 oz445.714 r0 (Instance 0)
 Move table: 0x07000362
 Cosmetic loadout: 0x70008653
   melee: dagger
State stack:
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by bcp19** [comment]
Spider in Haudh Lin
Selection: 0x0314685000000005
 DID: 0x70008009
 Loc: bx70 by133 c0 ox132.028 oy42.6418 oz336.355 r214 (Instance 0)
 Move table: 0x070001C3
State stack:
(Wander)
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by bcp19** [comment]
> Not a mob, but a pathing NPC issue: Labourer cannot walk up the stairs
> 
> Selection: 0x031F3FA000000477 (0x041F3FA0000000D3) DID: 0x70006FBF Loc: bx243 by250 c289 ox-5.60824 oy84.3089 oz-199.564 r129 (Instance 0) Move table: 0x070001E7 State stack: (Patrol) default patrol @ 0.5x (Idle) Melee combat mode: combat_monster Ranged combat mode: combat_monster
> 
> You are at: bx243 by250 c384 ox-1.98379 oy84.2057 oz-199.616 r196 (Instance 0)

I noticed this NPC starts down in the Thorin's Hall beer hall and takes about 2-3 minutes to walk up and get stuck

**Comment by echoes-emu** [comment]
Closing as there seem to be no more mobs here. @soakheart please review your comment above, I checked the stone and it looked OK but I'm not sure if you fixed it already or what the problem was
