### ISSUE TITLE
Agnes Martlet does not lean where she suppose to

### ISSUE THREAD

**Issue by Grimbatul** [echoes-emu/echoes-bt#725]
The Npc called Agnes Martlet she doesnt lean where she supposto lean in Amon Raith.
You are at: bx117 by139 c0 ox77.841 oy130.825 oz519.049 r185 (Instance 0)
![resim](https://user-images.githubusercontent.com/122386923/212153767-9bc3a542-dd2e-4622-b645-572bc18d497f.png)

**Comment by MasterTeal** [comment]
Please post in megathread #682

**Comment by Grimbatul** [comment]
> 
Looks like you did Master me doing it again would be dublicate. But thank you.

**Comment by woodx319** [comment]
moved to megga thread :) cheers bois
