### ISSUE TITLE
Leechcraft/Tend the sick  cannot be used on self (LM) when traited with Proof against all Ills

### ISSUE THREAD

**Issue by SpinexLive** [echoes-emu/echoes-bt#727]
When the trait Proof Against All Ills is equipped on the Lore-Master the two skills Leechcraft & Ten the sick are no longer applied to yourself and can only be used if targeting a fellowship member.

**Comment by Stressy23** [comment]
It can be used on self when target forwarded is enabled

**Comment by SpinexLive** [comment]
Cannot use on self with or without target forward enabled

**Comment by Stressy23** [comment]
No I was saying that if your target forwarding is enabled, and a creature is targeting you, you can use leechcraft/cure on yourself. 

To give more information for the bug to help the devs track down the source better

**Comment by SpinexLive** [comment]
> No I was saying that if your target forwarding is enabled, and a creature is targeting you, you can use leechcraft/cure on yourself.
> 
> To give more information for the bug to help the devs track down the source better

sorry my mistake :)

**Comment by echoes-emu** [comment]
Fixed, will require more testing though
