### ISSUE TITLE
Error in displaying the time in a letter about an auction sale

### ISSUE THREAD

**Issue by rabekon** [echoes-emu/echoes-bt#728]
Время отображается некорректно в письме с аукциона.

![image](https://user-images.githubusercontent.com/122410042/212159615-1467cadc-3986-43ff-8c33-1079c63cc051.png)

**Comment by echoes-emu** [comment]
duplicate of #661, please use English in your reports!

**Comment by rabekon** [comment]
> duplicate of #661, please use English in your reports!

Oops, I got confused in two languages and was sure I was writing in English)) sorry.
