### ISSUE TITLE
Places of Dwarves Deed Issue (exploration deeds not advancing)

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#73]
Talked with a gm, apparently this was not an issue prior to alpha testing however, I cannot locate thorins gate despite going in and out about 20x so far, so its impossible to complete this deed.

![1](https://user-images.githubusercontent.com/99286164/153158376-67416e8a-762d-4fc1-8108-51e538958ba8.JPG)
![2](https://user-images.githubusercontent.com/99286164/153158377-55bd49ad-94e8-485d-8435-9c614ac38f70.JPG)

**Comment by echoes-emu** [comment]
Should be fixed now as per @tobbexx

**Comment by Scoobysnacks86** [comment]
Deed "places of the dwarves", Thorin's hall location cannot be discovered still.
