### ISSUE TITLE
Name of the kinship can be written in Cyrillic.

### ISSUE THREAD

**Issue by rabekon** [echoes-emu/echoes-bt#731]
Name of the kinship can be written in Cyrillic. For players without Cyrillic fonts these names are not displayed correctly.

with in-game cyrilic fonts:
![image](https://user-images.githubusercontent.com/122410042/212171304-d602f0ad-5342-49db-a9c5-c4ce2a8c1e7b.png)

without in-game cyrilic fonts:
![image](https://user-images.githubusercontent.com/122410042/212171491-7e840c89-0a17-46e0-a132-3442bf5d8ec6.png)

**Comment by echoes-emu** [comment]
We don't support translations, it's up to RU players to write their kin names using English letters if they want the kin to be recognizable by others

**Comment by rabekon** [comment]
> We don't support translations, it's up to RU players to write their kin names using English letters if they want the kin to be recognizable by others


It spoils the gaming experience for other players. It would be better to block the ability to use Cyrillic in kinship names, if possible.

**Comment by TurdFerguson79** [comment]
Is it possible to display blank spaces instead of question marks?  That might solve the issue while letting them have their kin name in Cyrillic if they choose?

**Comment by Invizet** [comment]
Creep names can actually be created in Cyrillic too. Reproduced in original EN GB client.

![Вася](https://user-images.githubusercontent.com/37710256/212413325-2ce8d859-4f54-492c-bc44-d68c6777639c.png)
![василий2](https://user-images.githubusercontent.com/37710256/212413348-cf1d144b-28b7-4b17-8d59-d34c2f48df9e.png)
![василий](https://user-images.githubusercontent.com/37710256/212413410-6d411092-eb61-4d9c-96dc-02f58a02978d.png)
