### ISSUE TITLE
[Quest] Gleaning the Field - Active grape-vines after completing the objective

### ISSUE THREAD

**Issue by Gilnaure** [echoes-emu/echoes-bt#735]
Celondim quest 'Gleaning the Field': after collecting grapes from six grape-vines in Limael's vineyard there are a few others that are still active. 

Quest giver loc:
bx68 by120 c0 ox23.3384 oy125.801 oz347.116 r14 (Instance 0)

**Example loc (the player shouldn't collect grapes from this one for it to remain active):** 
bx63 by122 c0 ox128.941 oy150.13 oz493.831 r149 (Instance 0)

**Grape-vine info:**
Selection: 0x0313F7A000000049 (0x0413F7A00000000C)
DID: 0x700072AE
Loc: bx63 by122 c0 ox127.814 oy149.524 oz493.782 r157 (Instance 0)

https://user-images.githubusercontent.com/122461442/212203860-0484361e-747f-4d13-a9f0-e27eeda5cbef.mp4

**Comment by MasterTeal** [comment]
I have noticed this same thing on the quest to pick up stones in the area around the large tree near Tuckborough.  Will update this comment with quest name and local later.

**Comment by Gilnaure** [comment]
The same issue is for Traps for the quest 'Hungry mouths to feed.'
Example loc:
bx66 by128 c0 ox4.12523 oy26.1752 oz447.229 r64 (Instance 0)

Info:
Selection: 0x03142800000000C3 (0x0414280000000013)
 DID: 0x7000939D
 Loc: bx66 by128 c0 ox4.96527 oy26.0371 oz447.064 r0 (Instance 0)

**Comment by echoes-emu** [comment]
Looks like a client issues, WNF
