### ISSUE TITLE
Instance: To Avert A War (Langlas Prologue Quest) Broken [CRASHES SERVER]

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#74]
Entering this quest seems fine, but when you reach the very first checkpoint, where he would normally get the ring above his head, asking you to advance the quest from there. The server crashes, it occurred twice, at the exact same moment, so it is definitely this moment. I also got a client crash/bug splat (i apologize, it never occurred to me at the time to record the bug splat, was talking with GM and told me to do it in the future) 
But this quest is uncompleted, and crashes the server when it reaches to this point.
(cant get the location due to it crashing when i get here) but its triggered at this campfire (first location of npc's checkpoint) after clearing in total 9 mobs.

![unknown](https://user-images.githubusercontent.com/99286164/153181186-33c5d268-2746-4bdb-a931-dc8bd7d7c4ea.png)

**Comment by echoes-emu** [comment]
Fixed in e16dbb92
