### ISSUE TITLE
Shadow of the White Hand NPC doesn't spawn during the night (Foredawn)

### ISSUE THREAD

**Issue by sluwe-vos** [echoes-emu/echoes-bt#742]
Saerdan's Spy is not near his location at Foredawn - night time. Checked twice

**Comment by sluwe-vos** [comment]
You are at: bx118 by120 c0 ox14.0933 oy74.3474 oz398.426 r10 (Instance 0)

**Comment by TurdFerguson79** [comment]
I noticed that even when spawning properly on Open Beta, night-only NPCs would not spawn during foredawn.  I assumed this was to prevent an issue with npcs despawning while players were interacting with them, since it is the last time period before it switches to day.

**Comment by bcp19** [comment]
I have noticed that these night spawning mobs (Lost Shade, Saeradan's Spy, Bill Ferny) have a tendency to not spawn if the server is rebooted during a night phase of the game, but will be there as soon at the cycle ti cay and back to night completes.

**Comment by echoes-emu** [comment]
Please verify that's it's actually night using the /servertime command

**Comment by bcp19** [comment]
During a server reboot today during the 'night phase', this NPC did properly respawn when the server came back up.

**Comment by woodx319** [comment]
- [ ] reliable repro w/ footage

**Comment by sluwe-vos** [comment]
![image](https://user-images.githubusercontent.com/15167869/231268115-8e102b23-bbfb-4f4e-9e5c-a99d39080c76.png)

there you go for a picture

**Comment by woodx319** [comment]
Watched him all through the night. spawned at nighttime and left once it hit Foredawn. Foredawn is not nighttime - /servertime pings 'It is day'. 

![ScreenShot00033](https://user-images.githubusercontent.com/104697795/231324665-10ea552b-283a-457f-90be-e8cf6f9bea09.jpg)
![ScreenShot00034](https://user-images.githubusercontent.com/104697795/231324673-6a9b2111-82a4-4351-abe3-b1209ed019fb.jpg)
