### ISSUE TITLE
The Search for Lalia: Does not auto compleet when the player is 21+

### ISSUE THREAD

**Issue by sluwe-vos** [echoes-emu/echoes-bt#743]
Pick up Quest: You are at: bx250 by157 c26 ox-12.1183 oy-26.7771 oz-198.61 r190 (Instance 0)
location quest autocompletion: You are at: bx114 by116 c0 ox2.54716 oy109.329 oz419.793 r12 (Instance 0)

Even after you cancel the quest and repick it, the quest will not compleet if you had it during a server crash

**Comment by sluwe-vos** [comment]
![image](https://user-images.githubusercontent.com/15167869/214854952-f3849990-6a01-4061-b6a3-a72d93a8edd3.png)

Hasn't changed. perhaps change the quest that it allows to talk to her rather than auto compleet

**Comment by sluwe-vos** [comment]
small update: it seems the quest won't auto compleet if you are 21 or above, rather than a server crash bug.

**Comment by echoes-emu** [comment]
Fixed
