### ISSUE TITLE
Quest drops still lootable after reaching quest requirement and sometimes not counting when looted

### ISSUE THREAD

**Issue by merloechoed** [echoes-emu/echoes-bt#749]
Not sure if it's WAI for the problem in the two videos that follow.

In the first video, the quest was at 9/10 pelts collected on purpose, then, lots of bears were killed for the purpose to make more than 1 pelt drop to loot, then we can see that even after reaching the 10/10 pelts for the quest requirement, the other pelts are still lootable.

In the second video we can see that only the 10 pelts required by the quest are removed when the quest is turned-in.

This might be WAI for SoA era, as of for the player to pay attention as how many drop he still needs to collect. But if it's a bug, looks like it lies in the player being able to loot a quest item when the quest requirement has already been met.

But in the last screenshot, that I posted in #718 but didn't notice at first glance, we can notice that sometimes quest drops don't count for the quest when looted, as there are 4 sickle-flies wings in the bag but in the quest tracker it shows only 3/4.

https://user-images.githubusercontent.com/122577244/212424227-ac301ba6-1498-4e02-80a5-8629e787cca7.mp4

https://user-images.githubusercontent.com/122577244/212424310-c1e85ee9-bf19-499e-80aa-a495135b3941.mp4

![ScreenShot00066](https://user-images.githubusercontent.com/122577244/212373757-c37eb052-2531-415b-9c62-0c464722642e.jpg)

**Comment by Stressy23** [comment]
WAI for SoA Era. 

Quest mobs will drop quest items until the quest is complete. Even if multiple drop, if you dont pick them up they keep dropping.

**Comment by woodx319** [comment]
bear massacre ..

I think this may be WAI for soa as it kind of generally forces you to be more aware of your quest items and many take up inventory places and things like that.
