### ISSUE TITLE
To Avert A War: teleporting out can get you stuck

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#75]
If you cancel to avert a war, you get ported inside of thrashi's lodge, its impossible to get out. If you manage to click on langlin to port back in to escape the lodge, you can cancel it again and get ported back inside.

Quite literally : "WE CANNOT GET OUT!"

![Capture](https://user-images.githubusercontent.com/99286164/153182592-9c028204-8f8a-4ed5-ad23-a66a35054d2e.JPG)
![lodge](https://user-images.githubusercontent.com/99286164/153182595-cf54c08b-222c-4e69-80e3-c76a3cd902e2.JPG)

**Comment by echoes-emu** [comment]
Possibly linked to #84

**Comment by echoes-emu** [comment]
Consolidating with other teleport bugs
