### ISSUE TITLE
Quest icon doesn't change when the re-taking timer is up

### ISSUE THREAD

**Issue by Gilnaure** [echoes-emu/echoes-bt#753]
Cancel any quest, and wait for the re-taking (5 minutes).

![lotroclient_aw3DqHJ10L](https://user-images.githubusercontent.com/122461442/212435469-c01b7edb-7eef-47c5-bcc2-e45e6c0dbb2f.jpg)

**Comment by MasterTeal** [comment]
Duplicate of #176
