### ISSUE TITLE
[Quest] On the Mend - Incorrect animation timings

### ISSUE THREAD

**Issue by Gilnaure** [echoes-emu/echoes-bt#754]
Incorrect animation timings for Lynx-mother during her drama sequence: when she kills a hendroval - the killing animation is played much later than a hendroval dies.

**Loc:**
bx65 by128 c0 ox127.89 oy81.6118 oz461.746 r237 (Instance 0)

**Lynx-mother info:**
Selection: 0x0314180000000119 (0x041418000000001D)
 DID: 0x70007FF2
 Loc: bx65 by128 c0 ox125.697 oy82.248 oz462.145 r95 (Instance 0)
 Move table: 0x070003D7
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: Yes

https://user-images.githubusercontent.com/122461442/212436027-395435e6-d903-467d-9f3f-1f2d11740711.mp4

**Comment by woodx319** [comment]
Duplicate https://github.com/echoes-emu/echoes-bt/issues/790
