### ISSUE TITLE
Mega Thread: NPC's you have to talk to before fighting cannot be looted after fight.

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#756]
Examples:
Malin
Oath-Breaker Captain
The Bk 10 person

The Oathbreakers
Quest Giver:
Mincham

Oath-breaker Captain:
Selection: 0x0317591000000017 (0x0417591000000007)
 DID: 0x70008185
 Loc: bx117 by145 c0 ox34.7461 oy63.8184 oz421.062 r117 (Instance 0)
 Move table: 0x070000CF
 Cosmetic loadout: 0x70008187
   melee: sword_big
   ranged: Bow
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_bow
KungFu NPC: Yes

You are at: bx117 by145 c0 ox35.1751 oy62.0402 oz421.011 r0 (Instance 0)

**Comment by bcp19** [comment]
Olnathron

Selection: 0x0316D8D000000136 (0x0416D8D000000011)
 DID: 0x70008042
 Loc: bx109 by141 c0 ox99.1761 oy36.6864 oz407.765 r106 (Instance 0)
 Move table: 0x070000CF
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: Yes

You are at: bx109 by141 c0 ox99.9191 oy36.0978 oz407.75 r217 (Instance 0)

**Comment by merloechoed** [comment]
Just experienced this with Malin too. 

You are at: bx114 by111 c0 ox23.7622 oy63.6016 oz470.511 r205 (Instance 0)

Selection: 0x031726F0000001BB (0x041726F000000006)
 DID: 0x7000770A
 Loc: bx114 by111 c0 ox22.4238 oy64.1013 oz470.701 r129 (Instance 0)
 Move table: 0x0700003B
 Cosmetic loadout: 0x700016F3
   melee: Mace
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by merloechoed** [comment]
Could it be that NPCs with the tag "KungFu NPC" set to "yes" can't be looted? If you can keep an eye on it too.

**Comment by bcp19** [comment]
No, the Huorns are all Kung Fu

**Comment by woodx319** [comment]
what makes us think they *should* be looted?

Some quest npcs will exist just for the quest -- do they have items that should be dropping? I'm familiar with some but not all of the npcs. the ch 10 angmarim for example is just a crow master that may just be an SOA-ism that they don't drop a few coins

**Comment by bcp19** [comment]
When you kill them, their bodies have the sparkles that indicate lootable items are on it. In Live, the bodies are lootable. As far back as I can remember, they were lootable.

**Comment by bcp19** [comment]
Bk 1 Ch 10 Andraste:
Selection: 0x03171720000000C8 (0x0417172000000009)
 DID: 0x700076A0
 Loc: bx113 by114 c0 ox114.096 oy102.038 oz399.084 r32 (Instance 0)
 Move table: 0x070001BD
 Cosmetic loadout: 0x70001227
   melee: sword_small
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: Yes

You are at: bx113 by114 c0 ox115.243 oy102.986 oz398.952 r168 (Instance 0)

**Comment by Nora-elhopanes** [comment]
Bk 4 Chapter 6 The Knowledge of the Onodhrim

Selection: 0x031AE6E000000089 (0x041AE6E000000002)
 DID: 0x70007DBC
 Loc: bx174 by110 c0 ox77.9071 oy101.048 oz618.565 r245 (Instance 0)
 Move table: 0x0700066B
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: Yes

You are at: bx174 by110 c0 ox76.4369 oy106.437 oz618.658 r117 (Instance 0)

**Comment by bcp19** [comment]
Quest: The last ingot
Quest giver: 
Halmur Stoneshaper

You are at: bx250 by131 c2 ox-4.18915 oy25.1371 oz-80.675 r3 (Instance 0)

Selection: 0x031FA8300000001D (0x041FA83000000002)
 DID: 0x7000012E
 Loc: bx250 by131 c2 ox-4.15638 oy26.8229 oz-80.6236 r131 (Instance 0)
 Move table: 0x070001E7
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

Quest Mob:
Hjortur

You are at: bx185 by117 c0 ox35.9155 oy96.6269 oz1001.17 r80 (Instance 0)

Selection: 0x031B97500000007B (0x041B975000000006)
 DID: 0x70003834
 Loc: bx185 by117 c0 ox37.3158 oy96.2812 oz1001.13 r216 (Instance 0)
 Move table: 0x070001E7
 Cosmetic loadout: 0x7000132F
   melee: hatchet
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by bcp19** [comment]
Quest: The Second Challenge
Quest Giver Arzhur
You are at: bx134 by156 c0 ox24.502 oy4.07646 oz420.068 r175 (Instance 0)

Selection: 0x031869C000000148 (0x041869C000000002)
 DID: 0x70002D09
 Loc: bx134 by156 c0 ox23.677 oy3.769 oz420.096 r77 (Instance 0)
 Move table: 0x0700003B
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

Quest Mob:
Donnan
You are at: bx133 by155 c0 ox0.0168304 oy53.7234 oz424.188 r173 (Instance 0)

Selection: 0x031849B00000001B (0x041849B000000002)
 DID: 0x70008407
 Loc: bx132 by155 c0 ox158.725 oy53.2383 oz424.005 r52 (Instance 0)
 Move table: 0x0700003B
 Cosmetic loadout: 0x70002D31
   melee: hatchet
State stack:
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by bcp19** [comment]
> Bk 4 Chapter 6 The Knowledge of the Onodhrim
> 
> Selection: 0x031AE6E000000089 (0x041AE6E000000002) DID: 0x70007DBC Loc: bx174 by110 c0 ox77.9071 oy101.048 oz618.565 r245 (Instance 0) Move table: 0x0700066B State stack: (Idle) Melee combat mode: combat_monster Ranged combat mode: combat_monster KungFu NPC: Yes
> 
> You are at: bx174 by110 c0 ox76.4369 oy106.437 oz618.658 r117 (Instance 0)

Quest Giver: Barachen

**Comment by bcp19** [comment]
> Just experienced this with Malin too.
> 
> You are at: bx114 by111 c0 ox23.7622 oy63.6016 oz470.511 r205 (Instance 0)
> 
> Selection: 0x031726F0000001BB (0x041726F000000006) DID: 0x7000770A Loc: bx114 by111 c0 ox22.4238 oy64.1013 oz470.701 r129 (Instance 0) Move table: 0x0700003B Cosmetic loadout: 0x700016F3 melee: Mace State stack: (Idle) Melee combat mode: combat_1h Ranged combat mode: combat_monster KungFu NPC: Yes

Quest Giver:
Addie Wheatley

**Comment by bcp19** [comment]
Quest: The Light of Hope 
Quest Giver: Crannog
You are at: bx133 by155 c0 ox45.7607 oy63.3985 oz420.777 r175 (Instance 0)

Selection: 0x031859B0000006D1 (0x041859B000000007)
 DID: 0x70002CDA
 Loc: bx133 by155 c0 ox44.7728 oy62.9599 oz421.093 r39 (Instance 0)
 Move table: 0x0700003B
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

Quest Mob: Uthagan
You are at: bx140 by163 c0 ox20.4466 oy116.525 oz382.541 r202 (Instance 0)

Selection: 0x0318CA30000003F1 (0x0418CA300000001F)
 DID: 0x700084C9
 Loc: bx140 by163 c0 ox17.9036 oy116.88 oz382.31 r69 (Instance 0)
 Move table: 0x0700003B
 Cosmetic loadout: 0x70002D31
   melee: hatchet
State stack:
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by bcp19** [comment]
Quests: The Blood Price & Blood Pact
Quest Giver: Lorne
You are at: bx141 by153 c0 ox127.768 oy44.9792 oz384.301 r157 (Instance 0)

Selection: 0x0318D990000000BE (0x0418D99000000005)
 DID: 0x700084CD
 Loc: bx141 by153 c0 ox126.71 oy43.99 oz384.328 r240 (Instance 0)
 Move table: 0x070001BD
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

Quest Mob: Iron Crown Commander
You are at: bx140 by155 c0 ox125.694 oy33.3328 oz400.506 r125 (Instance 0)

Selection: 0x0318C9B000000720 (0x0418C9B00000000B)
 DID: 0x700084B7
 Loc: bx140 by155 c0 ox125.313 oy31.8741 oz400.564 r11 (Instance 0)
 Move table: 0x0700003B
 Cosmetic loadout: 0x7000170C
   melee: sword_big
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: Yes

Quest Mob: Silk Lady
You are at: bx145 by159 c0 ox28.1673 oy129.58 oz419 r215 (Instance 0)

Selection: 0x031919F000000108 (0x041919F000000007)
 DID: 0x7000857F
 Loc: bx145 by159 c0 ox26.65 oy130.78 oz419.058 r91 (Instance 0)
 Move table: 0x070001BD
 Cosmetic loadout: 0x700012B2
   melee: hatchet
State stack:
(Interacting)
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by bcp19** [comment]
> Quest: The last ingot Quest giver: Halmur Stoneshaper
> 
> You are at: bx250 by131 c2 ox-4.18915 oy25.1371 oz-80.675 r3 (Instance 0)
> 
> Selection: 0x031FA8300000001D (0x041FA83000000002) DID: 0x7000012E Loc: bx250 by131 c2 ox-4.15638 oy26.8229 oz-80.6236 r131 (Instance 0) Move table: 0x070001E7 State stack: (Idle) Melee combat mode: combat_monster Ranged combat mode: combat_monster
> 
> Quest Mob: Hjortur
> 
> You are at: bx185 by117 c0 ox35.9155 oy96.6269 oz1001.17 r80 (Instance 0)
> 
> Selection: 0x031B97500000007B (0x041B975000000006) DID: 0x70003834 Loc: bx185 by117 c0 ox37.3158 oy96.2812 oz1001.13 r216 (Instance 0) Move table: 0x070001E7 Cosmetic loadout: 0x7000132F melee: hatchet State stack: (Idle) Melee combat mode: combat_1h Ranged combat mode: combat_monster KungFu NPC: Yes

That was Halmur after the quest was finished, this is his !info beforehand:

Selection: 0x031FA8300000000A (0x041FA83000000002)
 DID: 0x7000012E
 Loc: bx250 by131 c2 ox-4.15638 oy26.8229 oz-80.6236 r132 (Instance 0)
 Move table: 0x070001E7
State stack:
(Interacting)
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

**Comment by bcp19** [comment]
The Scent of Mithril
Quest Giver
Bothwar

Selection: 0x03196960000001C1 (0x0419696000000013)
 DID: 0x7000865F
 Loc: bx150 by150 c0 ox42.2698 oy150.419 oz414.465 r84 (Instance 0)
 Move table: 0x070001E7
 Cosmetic loadout: 0x7000121A
   melee: sword_small
State stack:
(Idle)
Melee combat mode: combat_1hshield
Ranged combat mode: combat_monster
KungFu NPC: No

Intermediate NPC
Dwarf Miner
Selection: 0x03196960000001BA (0x0419696000000008)
 DID: 0x7000865E
 Loc: bx150 by150 c0 ox92.6015 oy127.461 oz420.645 r133 (Instance 0)
 Move table: 0x070001E7
 Cosmetic loadout: 0x70001218
   melee: sword_small
State stack:
(Idle)
Melee combat mode: combat_1hshield
Ranged combat mode: combat_monster
KungFu NPC: No

Angrim
Selection: 0x03195A10000000A0 (0x04195A1000000004)
 DID: 0x70008646
 Loc: bx149 by161 c0 ox67.1283 oy9.22295 oz372.644 r129 (Instance 0)
 Move table: 0x070001E7
 Cosmetic loadout: 0x700012C9
   melee: Mace
State stack:
(Idle)
Melee combat mode: combat_1hshield
Ranged combat mode: combat_monster
KungFu NPC: Yes

**Comment by echoes-emu** [comment]
Should be fixed now
