### ISSUE TITLE
If you sell a bound item, it will become unbound after buyback

### ISSUE THREAD

**Issue by soakheart** [echoes-emu/echoes-bt#759]

**Comment by Stressy23** [comment]
![image](https://user-images.githubusercontent.com/122374802/212476659-6e6367e9-84a3-4247-bf96-bb9f9f8e2141.png)
Not only that, It also repairs the item for free

**Comment by merloechoed** [comment]
Looks like this doesn't affect "Bind on Acquire" items.

**Comment by echoes-emu** [comment]
Fixed
