### ISSUE TITLE
Quest: Tangled Up (Free'ing Bersi from the spiders lair in Ered Luin) Major Pathing issue

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#76]
Bug: He has an extremely weird/buggy pathing issue.
Bug Exact Location: You are at: bx69 by131 c0 ox3.89568 oy16.5604 oz399.362 r34 (Instance 0)

Information:
When escorting Bersi from the spider lair, he gets to these coordinates listed above -> Picture example
![Capture](https://user-images.githubusercontent.com/99286164/153193461-1de662dc-773b-43ef-8524-79f859727464.JPG)
[died writing this xD]
He gets to this circled location, bugs out and then turns around and paths all the way back through (looked at first like he was resetting) but then he runs off and goes past the spider queen and up the cliff, along the edge (almost dropping off), he then comes into the same spot he bugged at, but  from the other side, and then completes and finishes.
This pathing issue leads to adding about another 4 minutes onto the quest due to fighting about 10+ more mobs as he goes off on a little adventure.

**Comment by echoes-emu** [comment]
This should no longer happen
