### ISSUE TITLE
Quest - North Downs -  Herbs and Simples loots still stay in bag after completing the quest.

### ISSUE THREAD

**Issue by Grimbatul** [echoes-emu/echoes-bt#760]
Once you complete the quest the items has been collected does not dissapear from bag
![herbs](https://user-images.githubusercontent.com/122386923/212469978-ce41e4af-703c-4c23-9cfd-ee7183a9622d.jpg)

**Comment by MasterTeal** [comment]
#718

**Comment by woodx319** [comment]
Merging https://github.com/echoes-emu/echoes-bt/issues/718
