### ISSUE TITLE
Creep NPCs stuck at the gate Steps of Gram

### ISSUE THREAD

**Issue by SpinexLive** [echoes-emu/echoes-bt#762]
3 NPC's are stuck at the gate of creep play rather than exiting to the world.

You are at: bx157 by139 c0 ox62.5594 oy133.464 oz474.209 r7 (Instance 0)

![image](https://user-images.githubusercontent.com/74355368/212484470-112301c8-3486-492c-bb42-b13d820881cf.png)

**Comment by woodx319** [comment]
Moors is not implemented at all yet so they dont want us githubbing it ..yet. 

stay tuned. happy weekend :)
