### ISSUE TITLE
Quest: Plundered port.the item left after collecting the required amount

### ISSUE THREAD

**Issue by Lommeliel** [echoes-emu/echoes-bt#763]
The item remained active after collecting the required amount to complete the quest

Selection: 0x031448100000027F (0x0414481000000008)
 DID: 0x700033E2
 Loc: bx68 by129 c0 ox99.0741 oy62.671 oz341.853 r0 (Instance 0)
![image](https://user-images.githubusercontent.com/122546283/212484697-65568d27-b478-48f8-be17-1ed024751382.png)

**Comment by MasterTeal** [comment]
See #735

**Comment by echoes-emu** [comment]
Client visual bug,  WNF
