### ISSUE TITLE
Burglar Aim skill

### ISSUE THREAD

**Issue by Gothicthorn** [echoes-emu/echoes-bt#768]
When using Aim to get a crit on rare occasions no crit is delivered but normal damage. It only happens rarely but I started to noticed it recently thinking I missed my attack only to see it was a genuine hit on my target.

**Comment by woodx319** [comment]
I've never had an issue with Aim -- so are you getting a Critical hit that is not actually hitting for what it says it does? (For example does it say 167 on screen but then only hit for 60 or something)

Can you provide screenshots or short video? @Gothicthorn

**Comment by MasterTeal** [comment]
I have experienced this a bit too. Make sure you wait for the aim buff to appear in your buffs. I've found if you press aim and immediately queue another skill like surprise strike it can fire before the aim buff gets applied. This may be a client-server latency issue?

**Comment by woodx319** [comment]
I was able to reproduce this - I feel very strongly this is working fine. The timing for this to happen is very close to it being too fast where the first skill gets overridden (no matter what skills you are cueing). 

Slowing down just a tiny little bit this will 100% never happen gotta let the game tick register the aim skill 

Vid and discussion: Reproduction is at roughly 3:30 
https://youtu.be/0DItZqymPSM
