### ISSUE TITLE
Quest: Assault on Rath Teraig - MATHI keeps playing his idle combat animation after the camp event finishes

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#77]
**Bug Location:** Inside the Assault on Rath Teraig Prologue
**Bug Event:** Mathi remains in combat after the fighting stops, swinging wildly at nothing, even after you progress, he skates along the floor toward the goblin javelins when that event procs, and he continues swinging while he glides, looks weird as hell.
**Bug Occurance:** Happens at the 3rd checkpoint of the quest. after stopping at the dwarf, and then the 2 elves at the barricade, you enter the circled area with the tents and encounter mathi, who then does all his show boating axe swinging to nothing in paticular. Dwarves, forever the coolest race ;)

![Capture](https://user-images.githubusercontent.com/99286164/153238158-731694e2-b4b9-480a-8e91-e4294ad08e84.JPG)

**Comment by echoes-emu** [comment]
Mentioned here: #589
