### ISSUE TITLE
A Deal Gone Sour

### ISSUE THREAD

**Issue by Invizet** [echoes-emu/echoes-bt#773]
NPC stays in starter position (like on Loc below, before accepting the quest) each time he loses agro (mobs died). 

Selection: 0x0318773000000512 (0x041877300000000F)
DID: 0x700007CF
Loc: bx135 by115 c0 ox57.2317 oy79.6343 oz393.993 r182 (Instance 0)
Move table: 0x0700003B
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: Yes

![eoa5](https://user-images.githubusercontent.com/37710256/212556288-878da6fd-feac-4ed0-9c35-f148ef3df165.png)

**Comment by woodx319** [comment]
_each time he loses agro (mobs died)._

Can you explain this in a different way, please? he's not attacking  mobs or what? @Invizet
