### ISSUE TITLE
Minstrel Skill - Triumphant Spirit Draws attention from everything

### ISSUE THREAD

**Issue by Grimbatul** [echoes-emu/echoes-bt#774]
The minstrel skill called Triumphant Spirit when used draw attentions from fellows pets as well. (LM Pet and Cappy Pet)

**Comment by Nora-elhopanes** [comment]
https://www.youtube.com/watch?v=7mtfDmDnrLw&t=2s&ab_channel=mats%26stellanlarsson

**Comment by Grimbatul** [comment]
#771 related with this skill bug i believe. Because i used it there as well.

**Comment by echoes-emu** [comment]
Fixed
