### ISSUE TITLE
Boars despawn north of bree up the hill

### ISSUE THREAD

**Issue by sluwe-vos** [echoes-emu/echoes-bt#776]
You are at: bx118 by120 c0 ox42.4058 oy157.449 oz374.607 r226 (Instance 0)
![Boar](https://user-images.githubusercontent.com/15167869/212577702-48fa277d-a3d8-4f06-ae0b-305f2a1d5b48.jpg)

Below in the boar valley if you pull boars up the southern hill they despawn

**Comment by woodx319** [comment]
To clarify you mean de-spawn as in disappearing, right?

**Comment by woodx319** [comment]
can you provide a *!info* on one of those disappearing boars please @sluwe-vos

**Comment by sluwe-vos** [comment]
so it is fairly difficult to get information after a boar despawns :D , but this was on the exact location they despawn

Selection: 0x0317679000000183
 DID: 0x70007717
 Loc: bx118 by121 c0 ox30.5426 oy1.1528 oz370.292 r122 (Instance 0)
 Move table: 0x0700039B
State stack:
(Combat)
(Wander)
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

![image](https://user-images.githubusercontent.com/15167869/212593019-f4778afd-012b-4056-9431-5b365cb9610e.png)

the picture was made 1second before despawning

**Comment by echoes-emu** [comment]
Merging with #907
