### ISSUE TITLE
Stealth mobs do not attack unless they are revealed.

### ISSUE THREAD

**Issue by sluwe-vos** [echoes-emu/echoes-bt#785]
If this is how things used to work back then sorry

Every stealth mob in the game remains hidden and does not attack. Even when a player is literally standing next to them, they do not ambush. Stealth mobs only attack once the player can physically see them. I believe a stealth wolf in Minas Eriol for example should have an aggro radius and not wait for the player to reveal their location

**Comment by woodx319** [comment]
> Stealth mobs only attack once the player can physically see them

Yeah the game kind of gives you a chance to see and almost 'trigger' the stealth mob, this way also the stealth mobs aren't just smacking you out of nowhere lmao. Going to close for now as it sounds WAI to me, but feel free to record a video as well and post - that would give us a better look.
