### ISSUE TITLE
Entering into Torech-i-Bogbereth (Angmar) crashes the client

### ISSUE THREAD

**Issue by rabekon** [echoes-emu/echoes-bt#786]
I repeated this action two times.

Symptoms: drop in fps, small spiders are stacked in each other in large numbers (this has not been fully tested, as there is little time to review this).

https://www.youtube.com/watch?v=UM1ZxkguUjo&ab_channel=%D0%A0%D0%BE%D0%BC%D0%B0%D0%BD%D0%91%D0%BE%D1%80%D0%BE%D0%BD%D0%B8%D0%BD

![image](https://user-images.githubusercontent.com/122410042/212680729-551c3e99-124d-4ea1-b7a2-d259aeb1f546.png)

**Comment by rabekon** [comment]
> The screenshot clearly shows a client crash. The server doesn't seem to be affected

But immediately after that the server became unavailable.

**Comment by rabekon** [comment]
> The screenshot clearly shows a client crash. The server doesn't seem to be affected

Now, server crash again near bogbereth lair 
![image](https://user-images.githubusercontent.com/122410042/212717130-f2df4ac5-38da-46bc-87e2-f413c916ac4a.png)

**Comment by rabekon** [comment]
please, check spawn mobs in lair...it looked broken when i got there the first time

**Comment by rabekon** [comment]
> The screenshot clearly shows a client crash. The server doesn't seem to be affected

https://www.youtube.com/watch?v=vBPEQVN4vbE&ab_channel=%D0%A0%D0%BE%D0%BC%D0%B0%D0%BD%D0%91%D0%BE%D1%80%D0%BE%D0%BD%D0%B8%D0%BD

**Comment by echoes-emu** [comment]
Fixed
