### ISSUE TITLE
Quest chests don't generate items for all fellowship members

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#79]
for the quest The First gear, you have to loot this chest. One person in our part looted it and now nothing is respawning in the chest
![The first gears](https://user-images.githubusercontent.com/99280428/153259737-9f265b24-5a6a-4435-9192-88fe044405b8.png)

**Comment by bensbengittingit** [comment]
Most recent one I found was in the quest

Spider Gems
You are at: bx130 by141 c0 ox38.3613 oy68.8731 oz413.762 r114 (Instance 0)

**Comment by tobbexx** [comment]
Played Out
bx126 by146 c0 ox105.588 oy66.6768 oz497.135 r214 (Instance 0)

**Comment by tobbexx** [comment]
Defending The Bridge
bx119 by136 c0 ox18.1154 oy130.523 oz482.813 r31

**Comment by echoes-emu** [comment]
The Lost Map
bx126 by149 c0 ox96.8096 oy49.9239 oz466.548 r19

**Comment by echoes-emu** [comment]
Should be fixed in b1b72a82
