### ISSUE TITLE
LM Pet (raven) pathing issue in Ered Luin

### ISSUE THREAD

**Issue by menthur** [echoes-emu/echoes-bt#791]
Raven pet has problem to follow the player. It's stuck in a permanent loop trying to find a path to the player character.

You are at: bx52 by137 c0 ox126.88 oy101.58 oz661.73 r69 (Instance 5)

![ScreenShot00020](https://user-images.githubusercontent.com/122735660/212782746-af21e150-0185-41cb-ad26-97ed87dfcb79.jpg)

**Comment by echoes-emu** [comment]
Cannot reproduce, reopen if you see this again
