### ISSUE TITLE
LM pet (raven) disappears visually in specific area in Ered Luin

### ISSUE THREAD

**Issue by menthur** [echoes-emu/echoes-bt#794]
When you step into area:

You are at: bx63 by118 c0 ox151.476 oy95.55 oz483.95 r94 (Instance 0)

and summon your LM raven pet, it disappears after a few seconds visually, although still technically summoned. However, you cannot order the pet to attack.

Raven summoned:
![ScreenShot00021](https://user-images.githubusercontent.com/122735660/212808662-53cb60dc-e600-436f-aa06-149c8de9fe4b.jpg)

Raven disappearing:

![ScreenShot00022](https://user-images.githubusercontent.com/122735660/212808701-05f984f2-494c-4f6a-befe-f2145e886bd7.jpg)

Moved to area:
You are at: bx64 by118 c0 ox6.9439 oy147.885 oz488.796 r112 (Instance 0)

and ordered pet to follow me. Pet didn't follow. I unsummoned and resummoned pet and at this location all is WAI again.

![ScreenShot00023](https://user-images.githubusercontent.com/122735660/212808937-8ee6a6d0-3042-4d59-aa11-a4eef5dd2d9b.jpg)

**Comment by echoes-emu** [comment]
Merging with #907
