### ISSUE TITLE
Instance: Garth Agarwen - Wolfhouds not affected by some skills while their masters are alive

### ISSUE THREAD

**Issue by merloechoed** [echoes-emu/echoes-bt#795]
The Créoth Disciples' allies, the Wolfhouds, are not affected by some skills, from lore-masters alone are the "Gust of Wind" and "Cracked Earth" skills, while their masters are alive. Check video.

Happens to more than one wolfhound ally.

https://user-images.githubusercontent.com/122577244/212814567-c8e9bc2a-a587-4db1-a039-727e977fd019.mp4

You are at: bx152 by119 c0 ox57.5787 oy151.285 oz346.704 r120 (Instance 2)

Selection: 0x0319877002000052
 DID: 0x7000047F
 Loc: bx152 by119 c0 ox57.2499 oy149.094 oz346.729 r6 (Instance 2)
KungFu NPC: No

**Comment by woodx319** [comment]
merging with main :)

https://github.com/echoes-emu/echoes-bt/issues/329

**Comment by merloechoed** [comment]
Just tested this outside the instance. Same problem happened to a pet/ally summoned by a Shambling Wight. Issue needs to be reopened.

**Comment by MasterTeal** [comment]
Seems like a duplicate of #667
