### ISSUE TITLE
Muster Courage cures fear auras

### ISSUE THREAD

**Issue by Nora-elhopanes** [echoes-emu/echoes-bt#797]

**Comment by MasterTeal** [comment]
I think this is WAI as long as it reapplies on the next tick of the aura.

**Comment by woodx319** [comment]
Do you have an example @Nora-elhopanes ? I assume something in GA when you guys ran maybe??

**Comment by Nora-elhopanes** [comment]
Yes @woodx319 , the wight auras. I can find somewhere to check it, I assume it should work in the barrows as well. Might be WAI

**Comment by Nora-elhopanes** [comment]
Example location
You are at: bx151 by117 c0 ox8.30543 oy9.09974 oz377.466 r141 (Instance 0)

As for if it's WAI if the dot reapplies, I stood near two wights for two minutes and aura did not reappear after being cured.

**Comment by echoes-emu** [comment]
Fixed, the aura re-applies pretty much instantly after being cured now
