### ISSUE TITLE
Swimming Goblin in Noglond, Ered Luin - Not attackable and does not attack

### ISSUE THREAD

**Issue by menthur** [echoes-emu/echoes-bt#798]
spawned close to the goblin fortress in Noglond. Mob is not attackable, and does not attack.

location:
You are at: bx56 by130 c0 ox52.3507 oy112.321 oz548.584 r182 (Instance 0)

mob:
Selection: 0x0313882000000026
 DID: 0x70007F28
 Loc: bx56 by130 c0 ox49.1375 oy109.665 oz520.669 r32 (Instance 0)
 Move table: 0x0700018E
 Cosmetic loadout: 0x700017CF
   melee: Mace
State stack:
(Wander)
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: No
![ScreenShot00025](https://user-images.githubusercontent.com/122735660/213018326-ddede8d3-b0c0-4ebc-a048-f291f0a057e9.jpg)

**Comment by MasterTeal** [comment]
#716

**Comment by menthur** [comment]
closed. moved to #716
