### ISSUE TITLE
Instance sky settings persist after leaving Q: Book 1 Chapter 3: Blackwolds Broken

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#80]
Bug location: Volume 1: Book 1 Chapter 3: Blackwolds Broken
Bug: Visual Bug, Screen becomes gloomy and very dark, close to the character, obscuring the game and players ability to see.

![1](https://user-images.githubusercontent.com/99286164/153264636-e149f2a2-571a-4269-a816-34edab531854.JPG)
After leaving this chapter, you virtually cannot see anything.

After relogging
![2](https://user-images.githubusercontent.com/99286164/153264697-fc4c0ea8-99f8-428c-95f7-eb1e53e16e0f.JPG)

not sure what could be causing it.

**Comment by echoes-emu** [comment]
Instance sky no longer persist since 9ef32f9f
Not sure if the sky handling is 100% but at least it's better now
