### ISSUE TITLE
Items that drop from mobs that start quests in the Trollshaws do not work

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#806]
Several quest items that from from the corresponding animals, will give you a quest box when you click on them, but the quest will never add to your log when you accept it.

70007CD8: Perfect Boar-tusk[e] (1/1 QuestItem)
70007D60: Perfect Bear-hide[e] (1/1 QuestItem)
70007D98: Perfect Lynx-hide[e] (1/1 QuestItem)
70007D9C: Unique Lynx-hide[v] (1/1 QuestItem)

Quest IDs:

70007CD9: [Trollshaws(34) "Boar-tooth Dagger"]: NPCTalk, InventoryItem
70007D61: [Trollshaws(36) "Bear-hide Armour"]: NPCTalk, InventoryItem
70007D99: [Trollshaws(37) "A Superior Lynx-hide Cloak"]: NPCTalk, InventoryItem
70007D9A: [Trollshaws(37) "Lynx-hide Cloak"]: NPCTalk, InventoryItem

If you use the !quest <id> you can give yourself the quests... so something is not working in there.

**Comment by echoes-emu** [comment]
Fixed
