### ISSUE TITLE
Items with 3 or potential more stats dont update the resistances of the character correctly

### ISSUE THREAD

**Issue by Schaumkus** [echoes-emu/echoes-bt#808]
There is an issue with items, that have 3 or more stats. 
The resistances of the character, wound, poison and disease dont update correctly after equipping such an item. The numbers decrease instead of increasing.

F.e. Naerandir's Necklace which has +7Vitality +7Will and +4Fate.
Equipping this item decreases the wound, disease and poison resistance by 0.2%. Fire and Fear resistance increases by 0.5%, as shown in the pictures.

![1](https://user-images.githubusercontent.com/123096264/213483809-0dd91b1c-e6c2-4696-b5c1-44e5d19affda.png)
![2](https://user-images.githubusercontent.com/123096264/213483817-758ce03a-0539-4f6a-8685-29d86680d7cb.png)
![3](https://user-images.githubusercontent.com/123096264/213483820-70f2e354-2610-45e1-a940-e3beffdc63d4.png)

**Comment by bcp19** [comment]
I had a similar issue, as you can see, wound, disease and poison mitigations all dropped by .3% just by adding boots with 4 stats on them
![image](https://user-images.githubusercontent.com/122328856/213601200-4a103127-7685-4467-b156-650ab9962a3a.png)
![image](https://user-images.githubusercontent.com/122328856/213601219-df3424c5-4e8d-4eb3-a184-70541f247f9e.png)
