### ISSUE TITLE
Book 6 Chap 7 text has typo

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#811]
When you get to Braigiar at Gabilshathur, the quest text has a typo in it.
Correct text:

Braigiar: 'Who are you? If you are not a servant of the Shadow of Angmar, how then did you pass through Rammas Deluon and not perish?
'Corunir sent you? That is joyous news! Your coming is as a trumpet of victory to us!'

Selection: 0x0319696000000081 (0x0419696000000017)
 DID: 0x700011C4
 Loc: bx150 by150 c0 ox56.4005 oy109.921 oz404.226 r190 (Instance 0)
 Move table: 0x0700003B
 Cosmetic loadout: 0x70001215
   melee: dagger
State stack:
(Idle)
Melee combat mode: combat_1hshield
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by echoes-emu** [comment]
Client-side content? WNF
