### ISSUE TITLE
Trolls in the Trollshaws do not threaten to attack

### ISSUE THREAD

**Issue by TurdFerguson79** [echoes-emu/echoes-bt#812]
Despite a red vitals bar, they're currently passive enemies.  I don't remember this as an SOAism

**Comment by bcp19** [comment]
Which trolls? You need to add a !info to help out. Also, you sure you weren't running !invis?

**Comment by TurdFerguson79** [comment]
Well, it was all trolls, but you were right--it was an !invis issue

I rarely use it, so I didn't realize it persisted between sessions, since most of the other cheat codes seem to reset when you log out.

My mistake :D
