### ISSUE TITLE
Shire - Needlehole - Quest Item Wrong Label

### ISSUE THREAD

**Issue by menthur** [echoes-emu/echoes-bt#818]
You need to defeat some Dourhand Dwarves in Rushock Bog to obtain their orders. That Quest Item is correctly labeled in your inventory once picked up as "Dourhand Orders". But if you right click it to read it, the title of that item reads "Text Item" instead of "Dourhand Orders"

**Quest NPC Ulfar (Needlehole):**
Info:
Selection: 0x0315878000000675 (0x041587800000000F)
 DID: 0x70000DEB
 Loc: bx88 by120 c0 ox92.4506 oy96.3985 oz350.208 r213 (Instance 0)
 Move table: 0x070001E7
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

**Loc:**
You are at: bx88 by120 c0 ox90.0671 oy99.1003 oz350.184 r66 (Instance 0)

**Screenshot:**
![ScreenShot00034](https://user-images.githubusercontent.com/122735660/213772147-6dc7b860-3918-4306-82a6-9bee63a3d9e2.jpg)

**Comment by rabekon** [comment]
> I have seen this on several other quests. If this turns out to not be a client bug I'll add to the list.

It's not a mistake. I am translating this game into Russian. And I know that this line in the texts of the game is transferred to all similar items.

![image](https://user-images.githubusercontent.com/122410042/213780655-db496657-14c4-47c7-a08a-a35cbcaf26a9.png)

**Comment by echoes-emu** [comment]
We have no control over the title of that window, WNF
