### ISSUE TITLE
The Quest "The Highwayman" has no patrols to defeat.

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#821]
For two days now, I have been roaming up and down the roadway through Imlad Balchorth all the way up to the Carn Dum watchers and I haven't yet found an Angmarim patrol to collect the money bag and orders from.

Quest giver:
Braigiar

Selection: 0x031969600000003F (0x0419696000000017)
 DID: 0x700011C4
 Loc: bx150 by150 c0 ox56.4005 oy109.921 oz404.226 r182 (Instance 0)
 Move table: 0x0700003B
 Cosmetic loadout: 0x7000121A
   melee: sword_small
State stack:
(Idle)
Melee combat mode: combat_1hshield
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by woodx319** [comment]
If that's the quest I am thinking of have you gone south? Like there is that dwarf camp (i think) up the hill. drop down, break legs. I think I always found them then going south down that road. might be thinking of wrong quest as well

**Comment by bcp19** [comment]
I started out searching the Orc camp on the northern side of Malenhad cause I got the quest in Gabilshathur, but then I read the text and saw it's in Imlad Balchorth. So I've run around in a lot of different places along a lot of roads and found nothing so far.

**Comment by TurdFerguson79** [comment]
In the back of the orc camp Mor Madhul there's a ramp around 4.3N, 27.7W that leads to some stairs.  I found an Angmarim Messenger and Angmarim Runner on that stairway--I believe those are the 2 mobs.

**Comment by bcp19** [comment]
Found the patrols thanks to this information, closing issue.
