### ISSUE TITLE
Burglar Improved Riddle May Be Playing Wrong Effect

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#829]
According to Book 11 patch notes:
The "Perplexing Riddle" Trait now applies a mesmerize with a 5 second grace period for damage versus a stun then mesmerize.

Currently, traited riddle applies a 5 second stun followed by a mesmerize (7000C3E1)

I have tested various effects:
700031DA: ComplexRiddle (PropertyModificationEffect)
700031DB: Induce Dazed (InduceCombatStateEffect)
700031DD: Induce Dazed (InduceCombatStateEffect)
7000C3E0: Induce Dazed (InduceCombatStateEffect)
7000C3E1: Induce Improved Riddle (InduceCombatStateEffect)
7000C560: Induce Dazed (InduceCombatStateEffect)

None of these effects apply what I would expect the correct effect to be, which is a daze effect that is not broken on damage for the first 5 seconds.  As I recall, this was key, because it means with the current implementation you cannot improved riddle a stun immune target, which you should be able to.

Still looking for a video capture from book 11 to confirm behavior, will update if I find one.

**Comment by woodx319** [comment]
I tested this and Improved riddle does not apply stun immunity and I *am* able to riddle stun immune targets.

I made a vid - sorry for game volume way too loud, but maybe just watch with sound off. 
Slapped some angmarim and was able to riddle them through their stun immy. 

Gonna close as non issue please re-open with new info or if misunderstanding 


[https://youtu.be/SF1whDiZtpY](url)
