### ISSUE TITLE
Path between Nen Harn and North Downs marked as OOB

### ISSUE THREAD

**Issue by TurdFerguson79** [echoes-emu/echoes-bt#836]
The land block starting (from the south) at:

bx130 by133 c0 ox159.815 oy97.4976 oz392.745 r0 (Instance 0)

and ending at

bx130 by133 c0 ox112.557 oy159.97 oz393.001 r0 (Instance 0)

is mistakenly marked as out of bounds

**Comment by echoes-emu** [comment]
Fixed
