### ISSUE TITLE
Mob occasionally disappears when running up slope after being attacked.

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#838]
I am standing at:
You are at: bx147 by170 c0 ox114.882 oy61.6664 oz553.226 r196 (Instance 0)

Iron Crown Warrior
Selection: 0x03193AA000000071
 DID: 0x700011FF
 Loc: bx147 by170 c0 ox89.6184 oy53.2026 oz541.196 r178 (Instance 0)
 Move table: 0x0700003B
 Cosmetic loadout: 0x7000122A
   melee: sword_big
State stack:
(Wander)
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

Hillmen Blood-Seer
Selection: 0x03193AA000000073
 DID: 0x7000857B
 Loc: bx147 by170 c0 ox95.9084 oy51.7467 oz540.946 r127 (Instance 0)
 Move table: 0x070001BD
 Cosmetic loadout: 0x70002CB8
   melee: Stave
State stack:
(Wander)
(Idle)
Melee combat mode: combat_2h
Ranged combat mode: combat_monster
KungFu NPC: No

Note: Seer started healing after first attack, then glided up the hill on her knees before disappearing just before reaching me. She respawned fairly shortly, attacked again, she ran about 1/2 way up the hill then glided the rest of the way and vanished... this one has been repeatable if NPC goes into some sort of induction, but will reach me and attack if there is no induction.

Also noticed, when blood-seer heals, she goes through the animation, but never recovers any morale.

**Comment by bcp19** [comment]
Correction, sometimes she will get morale during induction, but not every time.

**Comment by echoes-emu** [comment]
Merging with #907
