### ISSUE TITLE
Teleport sometimes moves player into geometry, or out of world

### ISSUE THREAD

**Issue by dmorcellet** [echoes-emu/echoes-bt#84]
I started a dwarf Champion "Glumlug". Took a few quests and tried to enter Thorin's Gate using the big gate.
I've been teleported inside, but probably somewhere below the floor level. Could move to the first big statue while seeing nothing except a gray screen.
Failed to make a screenshot: F11 gives "Failed saving screenshot to disk." => forget it, was a configuration issue on my Windows.

**Comment by dmorcellet** [comment]
In the end, I got stuck at:
You are at: bx243 by250 c307 ox-10.7717 oy143.669 oz-2246.47 r60 (Instance 0)

**Comment by dmorcellet** [comment]
And I cannot logout:
"You cannot log off while moving."

**Comment by Itheryn** [comment]
![image](https://user-images.githubusercontent.com/99286164/153303195-a69e5b1b-be6e-41ba-a8d9-579214a34d0f.png)

You are at: bx119 by118 c0 ox65.653 oy69.2429 oz419.678 r152 (Instance 0)

leaving prancing pony did this to me ^ same as it did with these above

**Comment by echoes-emu** [comment]
This is now fixed
