### ISSUE TITLE
Too Much Rested XP

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#844]
Characters gain rested XP much too quickly.  As I recall, it should be about 20-25% of the XP bar after being logged out for ~20-24 hours.  Rested XP gain may not be linear but may increase the longer the character is logged out, not sure about that.

Additionally, the maximum rested XP before it caps should cap at one full level worth of XP?

**Comment by echoes-emu** [comment]
Should be fixed now
