### ISSUE TITLE
Equipping Item with Clicky Doesn't Reset 5min Clicky Wait Cooldown

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#847]
Tested a few cases of equipping items with clickies:

~~Case 1: Equipping Item Not on Cooldown
Result: Item goes on cooldown for 5 minutes before clicky can be used.  WAI.~~

Case 2: Equipping Item on Cooldown From Equipping
Result: Equipped an item that I had equipped and unequipped (but never used the clicky ability) when it had about 2 minutes left on the 5 minute cooldown to use the clicky.  Cooldown did not reset back to 5 minutes, but should have.  **Not WAI**

~~Case 3: Equipping/Unequipping Item on Cooldown From Use
Result: Item keeps its cooldown (in this case 1 hour) whether equipped or unequipped. WAI~~

**Comment by echoes-emu** [comment]
Fixed
