### ISSUE TITLE
Enmity of the Wargs 2 does not start if you compleet it pre 30

### ISSUE THREAD

**Issue by sluwe-vos** [echoes-emu/echoes-bt#855]
![image](https://user-images.githubusercontent.com/15167869/215263986-bfc6bcdb-ae74-47f7-9e54-392074fdf826.png)

I have tried to see if it was a level issue, did it on a 23, 18 and 28 character.
Neither got part 2 of the deed.

**Comment by sluwe-vos** [comment]
![image](https://user-images.githubusercontent.com/15167869/215272691-f7de92ed-51f1-493d-9d79-6224e169a808.png)



> You have to be level 29 for it to start.

that is just blatently false.

**Comment by bcp19** [comment]
I'm just going by the Wiki. Maybe it was 30 back then

**Comment by sluwe-vos** [comment]
![image](https://user-images.githubusercontent.com/15167869/215281960-33231640-3d95-4825-83d5-f8f80b56ca13.png)

tried it on a level 50 character, same result.
Correct me if I am wrong but I think there has never been a deed gated behind levels in lotro

**Comment by bcp19** [comment]
A lot are

![image](https://user-images.githubusercontent.com/122328856/215282528-a3f65c21-0eef-41b4-b87c-a11df04f8212.png)

**Comment by sluwe-vos** [comment]
you closed the ticket?

**Comment by sluwe-vos** [comment]
I think you should be able to reproduce it by compleeting the deed before level 29. A friend of mine had the same issue. This will prevent the deed from reopening once you hit 29

**Comment by sluwe-vos** [comment]
![image](https://user-images.githubusercontent.com/15167869/215283510-d2c1134c-f385-4aad-96e4-d6ac9eaebc86.png)

yup just did the same with Hill-men deed. once I go back to 35 it does not start part 2 of the deed.

**Comment by bcp19** [comment]
When you made yourself level 29 and level 50, did you use the !lvl command? You might want to try making yourself level 28 and then !xp to get to 29 as otherwise I believe you have to log out and in before the level change takes effect fully

**Comment by sluwe-vos** [comment]
the character that first noted the issue was leveled WITHOUT CHEATS. I leveled with a buddy and we both noticed the bug with the warg deed

**Comment by bcp19** [comment]
I created a man character and !lvl 13 and started killing Wights and Wargs, which started Enmity I for both. Upon completing the Enmity I for both and killing a few extra for good measure, I !lvl to 18 and then !xp to get to 19. Neither Wights II or Wargs II would start. This seems to be tied into the Places of the Dwarves and the Ruins of the Breeland deeds in that if you "start" anything related to the deed before you are at level where you are actually able to start the deed, it is somehow flagged that you've been there/killed that. I even tried adding xp a bit at a time to hit each level... 20, 21, 22... 29, 30 and still neither Enmity deed would start.

**Comment by echoes-emu** [comment]
The advanced deed should now correctly unlock upon level-up
