### ISSUE TITLE
Missing NPC or Summon Item: Q: The Vale of Andrath

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#86]
Bug: Sharkey's Lieutenant is missing from South-Guard Ruins.
I checked every corner of the zone, he's not in some old spot that I dont remember I think, But actually missing from his actual spot.
I don't know why but i think there was a summon horn laying on the floor near where im stood that called him forth in SoA days. But either way, this is where he should be. But he isn't. So the quest is not advancable.

Bug Location: South-Guard Ruins / The Vale of Andrath (Bree-Land)
You are at: bx119 by110 c0 ox17.1337 oy54.3816 oz468.104 r126 (Instance 0)

![Capture](https://user-images.githubusercontent.com/99286164/153296780-6b3f1885-fedc-47fc-ab79-3d707900f158.JPG)

**Comment by echoes-emu** [comment]
The Lieutenant will spawn correctly after the next maintenance
