### ISSUE TITLE
Completing Deed Conquest of Ost Ringdyr crashes the server. 

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#863]
Lainedhel:

Selection: 0x031A887000000050 (0x041A887000000012)
 DID: 0x70007104
 Loc: bx168 by135 c0 ox99.5078 oy96.0814 oz578.478 r0 (Instance 0)
 Move table: 0x07000221
 Cosmetic loadout: 0x7000715C
   melee: sword_big
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by bcp19** [comment]
Apparently it's not the Captain General, but completing the deed Conquest of Ringdyr that crashes the server.

**Comment by bcp19** [comment]
Conqueror of Tol Ascarnen deed also crashes server

**Comment by echoes-emu** [comment]
Fixed
