### ISSUE TITLE
Bree lvl 1 Intro has bug

### ISSUE THREAD

**Issue by sluwe-vos** [echoes-emu/echoes-bt#869]
![image](https://user-images.githubusercontent.com/15167869/216606304-e78d55d1-2c05-48c0-8b5a-619f323c6145.png)

no NPC's show up until after log out and back in. did the lvl 1 amandir intro 3 times, same result each time

**Comment by bcp19** [comment]
I think it's your client, I just ran through it and all the NPC's were there without needing to relog

**Comment by sluwe-vos** [comment]
any suggestion how to fix this possible client issue? I think you could be spot on because I have been falling through terrain when leaving houses in bree

**Comment by bcp19** [comment]
Have you tried uninstalling the echoes launcher and re-running the setup? That would be a first step. I don't know if there is any way to verify if the data files are correct... I know there is a way to create CRC check for files, but don't know if those programs are single program of if they will do full folders.

**Comment by woodx319** [comment]
You can try this as well @sluwe-vos 

https://aka.ms/vs/17/release/vc_redist.x86.exe

**Comment by sluwe-vos** [comment]
did both things

I haven't encountered the issue again, tried it only once, will let you know if the problem reoccurs
