### ISSUE TITLE
Sally's chain

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#88]
![image](https://user-images.githubusercontent.com/14816951/153319212-177b7df7-eab7-47e3-aac9-c9f57eb2d268.png)

Sally's Chain is supposed to drop from any Blackwold located at Old Bauman's Farm, however, it dropped from a Blackwold that generally drops a Fishing pole (a few hundred metres away from the farm)

entity name; ''Blackwold Raider''
location approximately;  bx126 by120 c0 ox134.02 oy67.256 oz395.304 r28

Unsure if the Blackwold's at Baumans should have special properties regarding that quest.

**Comment by echoes-emu** [comment]
Fixed in 94569811
