### ISSUE TITLE
Race of (Man) Healing More than (Elves)

### ISSUE THREAD

**Issue by woodx319** [echoes-emu/echoes-bt#880]
I came across this by accident while testing all the champion traits. My elf got deleted and so I made a human.

**[Issue]**: Bracing attack at lvl 48 (with the trait) has a **446** tooltip. On my elf champ it indeed healed for **446**, however on my man champ it healed for **468**. It still had a **446** tooltip on the human. 

_I tried quite a few things since then messing around with it. I made sure none of the gear had inc healing or anything. I only had the skill traits equipped. I thought maybe that !traiting all was giving me the man passive heal but I made a new man champ and didn't trait all but only added the traits specifically. I did try on lvl 50s as well. I tried without the bracing trait too._ 

_5% of 446 is 22.3 so 446 + 22.3 gives us the 468. This makes me wonder if the man passive inc healing is popping on it. That passive shouldn't be popping without the trait actually equipped. Is it possible that using the cheats is making it apply maybe? I haven't had the dedication to level a champ up naturally to get the trait but something maybe some other people can mess with or look at._ 

**[How to replicate]-** make a new +char and then level to 50 with the dojo. Your values will be a little different as I was on lvl 48 chars. I also had the bracing attack class trait equipped at the time but the values are off without the trait as well. Your elf should heal for the bracing attack tool-tip while the human will heal for 5% more than the bracing attack tooltip. 

![Elf Heal21](https://user-images.githubusercontent.com/104697795/218812088-b1efa7a0-e9c0-4a02-8e2a-527c48d939d6.png)

**Comment by Extrima** [comment]
The man race has the "passive" trait: Easily Inspired (characteristics) which gives you "increased morale restoration" If you create a character you can see the different passives each race has at character creation

**Comment by Extrima** [comment]
![image](https://user-images.githubusercontent.com/2895940/218875195-36783ab6-f620-42b6-93ca-7a5b2de0756f.png)

**Comment by woodx319** [comment]
Ahhh ok yeah I keep thinking that is one that you slot. thanks! :) @Extrima
