### ISSUE TITLE
Is the quest "Siegecraft" missing an induction and an animation?

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#886]
When you click to remove the ballista locks, catapult pinions and trebuchet swing-arms, there is no induction and I seem to remember the siege engines collapsing in an animation. 

Catapult:

Selection: 0x031898800000006E (0x0418988000000009)
 DID: 0x700082DB
 Loc: bx137 by136 c0 ox66.7193 oy133.428 oz399.158 r225 (Instance 0)

Trebuchet:

Selection: 0x03186880000000B2 (0x0418688000000005)
 DID: 0x700082DD
 Loc: bx134 by136 c0 ox143.617 oy8.94146 oz369.133 r117 (Instance 0)

Ballista:

Selection: 0x031878800000007D (0x0418788000000008)
 DID: 0x700082D9
 Loc: bx135 by136 c0 ox91.3007 oy78.6294 oz393.609 r94 (Instance 0)

**Comment by echoes-emu** [comment]
Already mentioned here: #815
