### ISSUE TITLE
Possible bug on Quest "Dangerous Enterprise"

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#888]
When you approach Strawleys wagon you get a popup message and a crate behind the wagon can be clicked on, which spawns 2 Guaradan that run down the path towards you. But if you run back down the path immediately after clicking the crate, the Guaradan pause next to the wagon then run around it and back up the hill and despawn.

Crate:

Selection: 0x031A56B000000049 (0x041A56B000000009)
 DID: 0x7000B74B
 Loc: bx165 by107 c0 ox143.142 oy27.318 oz370.966 r1 (Instance 0)

Guaradan:

Selection: 0x031A56A00000003C (0x041A56A000000004)
 DID: 0x7000B6FE
 Loc: bx165 by107 c0 ox143.67 oy26.5278 oz371.831 r14 (Instance 0)
 Move table: 0x07000A1C
State stack:
(Combat)
(Patrol) default patrol @ 1x
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

Selection: 0x031A56A00000003D (0x041A56A000000005)
 DID: 0x7000B6FF
 Loc: bx165 by107 c0 ox138.605 oy23.9165 oz371.093 r36 (Instance 0)
 Move table: 0x07000A1C
 Cosmetic loadout: 0x700025BE
   melee: Spear
State stack:
(Combat)
(Patrol) default patrol @ 1x
(Idle)
Melee combat mode: combat_2h
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by echoes-emu** [comment]
This seems to be correct
