### ISSUE TITLE
Drop rate on the Iron Collar to start a quest seems very low

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#891]
I killed over 30 wargs before I got the collar to drop, I can't remember it ever taking that much on Live. Does anyone remember differently?

Roaming Warg

Selection: 0x031888A0000001ED
 DID: 0x70008317
 Loc: bx136 by138 c0 ox70.0844 oy38.1681 oz376.926 r154 (Instance 0)
 Move table: 0x07000210
State stack:
(Wander)
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: No

**Comment by echoes-emu** [comment]
Drop rates are reliable data
