### ISSUE TITLE
[Champion] Class Trait Bugs

### ISSUE THREAD

**Issue by woodx319** [echoes-emu/echoes-bt#898]
I have been testing all the champion **class traits** and am going to compile them all here to keep it a bit organized and so I can easily keep track of it. 

- [x] At the Ready
- [x] Blood Lust (c*)
- [x] Braced Against Defeat
- [x] Call of the Wild (To be tested)
- [x] Deadly Strikes (c*)
- [x] Deep Strikes (c*)
- [x] Eye of the Storm
- [x] Fervent Rage
- [x] Flurry of Blows
- [x] Heavy Shield Use
- [x] Patience (To be tested)
- [x] Stalwart blade
- [x] Swift to Anger
- [x] Time of Need
- [x] Winds of the Storm
- [x] Vicious Strikes (c*)

**Comment by woodx319** [comment]
Fervor damage bonus bug


This shows up on a number of traits that are supposed to passively _Increase Fervor damage bonus by 1.0%_

The bonus shows up on the fervor skill tooltip but it does not show up under character vitals and it does not seem to increase any damage. 


![ScreenShot00024](https://user-images.githubusercontent.com/104697795/220184949-02e33116-e1f1-4a75-93fe-89e17bf19f4a.jpg)

**Comment by woodx319** [comment]
### **Braced Against Defeat**

The AOE bonus works on this.
This does increase the healing from 3xx to 4xx.

What does *not* appear to be working is. The description states *provides additional moral for yourself **increasing a small amount for each enemy around you***

I tested this with one mob up to 6 mobs and it always heals for 468. Perhaps I am interpreting the wording wrong and this was a bug at the time but from the wording it seems like it should heal more at 6 enemies than against 1 enemy. 


![Elf Heal](https://user-images.githubusercontent.com/104697795/220185608-da36530f-9d23-4f75-8cee-32dcaa958cad.jpg)

**Comment by echoes-emu** [comment]
**Fervour damage bonus** - not sure how you established that it doesn't increase any damage but it's tested WAI (it does in fact increase all melee damage you do). Also not sure where it should show on the character sheet screen? If you mean "Melee Eff", that value is calculated and presented entirely by the client and we have no control over it. 

Please review

**Comment by woodx319** [comment]
> not sure how you established that it doesn't increase any damage

the character vitals tooltip and also the skill tooltip. And also I had done a small sample size test (was going to do more before posting) but it was too small because it's checking out now with a larger size.

20 hits
Wild attack average 
15% Fervour average damage 108.55
19% w/ four traits equipped 109.05

Auto attack
15% average 100.55
19% damage 102.5

**Comment by woodx319** [comment]
> Also not sure where it should show on the character sheet screen?

I'm going to make a vid real quick cuz i think easier to show than trying to screenshot

** will add

**Comment by echoes-emu** [comment]
I see, that's just a cosmetic issue
