### ISSUE TITLE
During the Epic Quest for Book 7 Chapter 5 NPC has error in dialogue

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#899]
When you bring the mithril and key to Litli he goes into a series of dialogue which should look like this:

Litli says: "I'll set the mithril in the bed of coals here."
Litli says: "There that won't take long."
Litli says: "Now, there's still a problem. Shaping mithril isn't an easy task."
Litli says: "Tales tell that a special shaping hammer is needed for such fine work as a key."
Litli says: "I've no such hammer though, nor have I ever seen one."
Litli says: "Best tell Dwalin that if I'm to complete this work for you, I'll need such a hammer."
Litli says: "Go on now, let him know."

Only he says this instead, inserting he into the sentence. May be a client side issue?

Litli says, ''Best tell Dwalin that if he I'm to complete this work for you, I'll need just such a hammer.''

**Comment by bcp19** [comment]
Selection: 0x031F3FA000000135 (0x041F3FA0000001D5)
 DID: 0x70009960
 Loc: bx243 by250 c396 ox-28.0374 oy295.47 oz-187.753 r103 (Instance 0)
 Move table: 0x070001E7
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

**Comment by echoes-emu** [comment]
Text is on the client, probably an early typo
