### ISSUE TITLE
Weapons/jewelry always equips to primary slot only, doesn't fill empty secondary slot

### ISSUE THREAD

**Issue by bensbengittingit** [echoes-emu/echoes-bt#90]
When you switch weapons the first slots is always used so if you are trying to switch to 2 1h weapons by pressing buttons and not dragging you just end up with 1 weapon in hand. This is very annoying for champ or burg or hunter or anyone else who can dual wield.

**Comment by echoes-emu** [comment]
This needs investigation, there's no indication in the game files that the item should equip anywhere else but the primary slot

**Comment by bensbengittingit** [comment]
Just to advocate for my class. I would hope that equipped gear can go into the 2nd slot ex: 1h weapons. Because if not then champion cannot weapon swap into 2 1hs. Also as a champion advocate Id say this is an important mechanic of the class and should be implemented by the release of beta if that is feasible. many champions would lament the delay of this function.

**Comment by echoes-emu** [comment]
Fixed in 818fe598
