### ISSUE TITLE
Jumping off a cliff while riding a horse allows you to keep 'riding'

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#900]
Note: You do need to keep holding down the forward motion key

https://www.youtube.com/watch?v=iodi4r_owDY

**Comment by woodx319** [comment]
to do: 
I'm going to try to find a spot where this happened to me on foot as well -- going to check with horse flying as well and see if it's all falls or just certain spots

**Comment by woodx319** [comment]
This appears to have been fixed 


https://user-images.githubusercontent.com/104697795/231344948-b5a3aaed-ba60-4859-9590-3a99b9c7bf07.mp4


https://user-images.githubusercontent.com/104697795/231345127-cf31e0c4-41f5-4381-8cb9-fc2142fb703c.mp4
