### ISSUE TITLE
Interactable quest object that opens a dialog isn't possible to use

### ISSUE THREAD

**Issue by Thrallmar** [echoes-emu/echoes-bt#902]
Nothing happens when pressing these types of objects:
Quest: Beyond the gloaming falls
Selection: 0x0315B95000000057 (0x0415B95000000007)
 DID: 0x70009819
 Loc: bx91 by149 c0 ox42.2845 oy50.7936 oz538.782 r61 (Instance 0)

Quest: Goblins and Spiders
Selection: 0x031677F000000428 (0x041677F00000000D)
 DID: 0x7000A24F
 Loc: bx103 by127 c0 ox11.0951 oy69.2032 oz385.019 r0 (Instance 0)

**Comment by echoes-emu** [comment]
Should be fixed
