### ISSUE TITLE
Vault: extra chests can be purchased before the player is high enough level

### ISSUE THREAD

**Issue by rabekon** [echoes-emu/echoes-bt#904]
If you buy additional chests 3 and 4, chests cannot be used by clicking on them.

![image](https://user-images.githubusercontent.com/122410042/222099233-cbb83dff-e068-4c96-b6a0-f40c4db7ed82.png)

Chests 3 and 4 can only be opened with the Inventory key ("I" by default).

![image](https://user-images.githubusercontent.com/122410042/222099701-e8915cca-154e-4a81-8c2e-2837c86a55dc.png)

**Comment by bcp19** [comment]
You are not high enough level to purchase them yet, that's why they show as locked. The bug should be 'Able to purchase extra bag space before you are at the proper level to"

**Comment by rabekon** [comment]
> 

I confirm this information. I have just done additional tests. This error really depends on the level of the player. Chests can be bought before they can be used.

LVL 30:

![image](https://user-images.githubusercontent.com/122410042/222346059-4ed3aab1-c281-477c-9a15-54e996b1c192.png)

LVL 50:

![image](https://user-images.githubusercontent.com/122410042/222346190-80736720-98ca-4af6-bb31-7f5aaca7b3bc.png)

**Comment by echoes-emu** [comment]
Fixed
