### ISSUE TITLE
Escort Vitals Don't Display HP Correctly 

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#91]
Hard to demonstrate by taking 2 pics with snip tool.
But, if you let the npc fight, the escort vital HP bar does not move, you then click on the npc and the escort vital will update.

![1](https://user-images.githubusercontent.com/99286164/153443022-0d997b5d-5a9e-4653-aac6-58fb55d079b0.JPG)
![2](https://user-images.githubusercontent.com/99286164/153443025-5da3ecff-2c47-4ebd-896d-073f1bffaf07.JPG)

**Comment by echoes-emu** [comment]
Fixed in cbfcc477
