### ISSUE TITLE
Quest :Missing the Meeting" is missing dialogue

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#910]
The following dialogue should happen once you update the quest in the bird and baby:

Jack Lewisdown says, "You have a message from Ronald?"
[Carlo Williams](https://lotro-wiki.com/index.php/Carlo_Williams) says, "That is a shame, I was hoping Ronald had finished his discourse on my book, 'The Place of the Boar.'"
[Carlo Williams](https://lotro-wiki.com/index.php/Carlo_Williams) says, "Did you hear that Owen, Ronald isn't making the meeting today."
[Owen Farfield](https://lotro-wiki.com/index.php/Owen_Farfield) says, "Hmmm? Oh, that is too bad. I was going to read from 'The Silvered Horn' tonight. Pity he won't hear it."
Jack Lewisdown says, "Well, you have our thanks for coming all this way to tell us about his absence."
Jack Lewisdown says, "I hope this book is as good as he claims."
Jack Lewisdown says, "It is not like Ronald to miss our meetings, I trust that he is working hard on his story and is not caught up in any silly games."

Quest ID: 70009A5D

Jack Lewisdown:

Selection: 0x0315971000000107 (0x0415971000000080)
 DID: 0x70009A56
 Loc: bx89 by113 c2 ox83.0072 oy-40.8748 oz-26.1247 r149 (Instance 0)
 Move table: 0x070000B1
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

**Comment by woodx319** [comment]
merged https://github.com/echoes-emu/echoes-bt/issues/926
