### ISSUE TITLE
In the Instance "The Bounty Hunter" the scripting needs work.

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#913]
Cuthbert Sprunt is present when he should walk in after several moments. Sprunt never activates.

Selection: 0x031679200300005A (0x0416792000000044)
 DID: 0x7000B257
 Loc: bx103 by146 c0 ox127.379 oy113.115 oz426.871 r137 (Instance 3)
 Move table: 0x0700003B
 Cosmetic loadout: 0x700007E7
   melee: Mace
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: Yes

NPC attacks as soon as you port in (should not be present yet)

Graham Hinchcliffe:

Selection: 0x031679200300005C (0x041679200000004F)
 DID: 0x7000B258
 Loc: bx103 by146 c0 ox143.017 oy115.68 oz426.871 r13 (Instance 3)
 Move table: 0x0700003B
 Cosmetic loadout: 0x70000EE4
   melee: sword_small
   ranged: Bow
State stack:
(Drama) drama_brigand_lose
(Combat)
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_bow
KungFu NPC: Yes
Drama: drama_brigand_lose

The dialogue is dependent on the player class and can be found here:

https://lotro-wiki.com/index.php/Quest:Instance:_The_Bounty-hunter

**Comment by woodx319** [comment]
merged https://github.com/echoes-emu/echoes-bt/issues/926
