### ISSUE TITLE
In the quest "Unfriendly Eyes in Ost Forod", you don't fail the quest if you die

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#916]
You respawn with the chest in hand. The quest will semi-fail if you enter the water, you have to go back and pick it up again

Quest ID: 700097E4

Quest Giver:
Robin Dunkley

Selection: 0x03167910000004A3 (0x0416791000000007)
 DID: 0x70009706
 Loc: bx103 by145 c0 ox21.1602 oy66.8439 oz479.667 r92 (Instance 0)
 Move table: 0x0700003B
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

**Comment by woodx319** [comment]
merged https://github.com/echoes-emu/echoes-bt/issues/926
