### ISSUE TITLE
Cosmetic Bug: Warspeech

### ISSUE THREAD

**Issue by Itheryn** [echoes-emu/echoes-bt#92]
![warspeech](https://user-images.githubusercontent.com/99286164/153484483-897c89e0-a871-4064-b130-a79890a55909.JPG)

Warspeech hands still active while warspeech isn't actually active

**Comment by echoes-emu** [comment]
The general problem with FX persisting was fixed a while ago, cannot reproduce this anymore. If it's still happening, please describe how to get to this state
