### ISSUE TITLE
Cannot complete instance "A Formal Complaint" due to scripting

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#923]
When you enter the house, you fight the chief's men and Will Tuffin runs out of the room but never activates once they are dead.

Quest ID: 70009A59

Quest Giver:
Hob Hillbrow

Selection: 0x03166810000000B5 (0x0416681000000004)
 DID: 0x700096E0
 Loc: bx102 by129 c0 ox146.725 oy2.27989 oz361.622 r207 (Instance 0)
 Move table: 0x070000B1
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

**Comment by woodx319** [comment]
merged https://github.com/echoes-emu/echoes-bt/issues/926
