### ISSUE TITLE
Instance "The Tomb of Elendil" issues

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#924]
Pathing issue
Selection: 0x031FA4F0030002EF (0x041FA4F0000000B3)
 DID: 0x7000984C
 Loc: bx250 by79 c505 ox-10.7171 oy410.611 oz-276.964 r20 (Instance 3)
 Move table: 0x0700003B
 Cosmetic loadout: 0x700007A0
   melee: sword_big
State stack:
(Patrol) default patrol @ 0.5x
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

Scripting:
Selection: 0x031FA4F003000300 (0x041FA4F0000000E6)
 DID: 0x70009850
 Loc: bx250 by79 c513 ox118.181 oy459.418 oz-281.594 r0 (Instance 3)
 Move table: 0x0700003B
 Cosmetic loadout: 0x70000460
   melee: hatchet
State stack:
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: Yes

Selection: 0x031FA4F00300030A (0x041FA4F0000000F1)
 DID: 0x70009853
 Loc: bx250 by79 c513 ox117.224 oy457.871 oz-281.594 r4 (Instance 3)
 Move table: 0x07000A0F
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster
KungFu NPC: Yes

Infinite spawning tomb sneak
Selection: 0x031FA4F00300036D (0x041FA4F00000019D)
 DID: 0x7000984F
 Loc: bx250 by79 c551 ox297.135 oy427.353 oz-295.764 r0 (Instance 3)
 Move table: 0x0700003B
 Cosmetic loadout: 0x70007BEF
   melee: dagger
State stack:
(Combat)
(Idle)
Melee combat mode: combat_dualwield
Ranged combat mode: combat_monster
KungFu NPC: No

Sneak falls through the stair when you climb them

Idalene also falls through the stairs, have to nuke to kill her as she never finishes here dialogue:

Idella Crypt-breaker says, "Where is it? It's not here?"
Idella Crypt-breaker says, "I was told it would be here! 'A stone of value beyond your dreams,' she said!"
Idella Crypt-breaker says, "No matter! I'll still turn a profit if I kill you and sell your belongings at Ost Forod!"

Gwindeth was present before Idalene was dead, I believe she runs in from the side after she dies.

After talking to Gwindeth, she runs through the falling water and fails to say her next lines:

Gwindeth says, "You will find the stone you seek through this passage, but heed my words with care."
Gwindeth says, "Do not wake Nornagol."
Gwindeth says, "It may be slow to waking, but it is a creature of hate and will destroy you if it can."
Gwindeth says, "Go now and hope that the memory of great Elendil smiles on your passing."

Many visual errors on way down to Nornagol, cannot see the floor or the walls in many places.

Gwindeth is already present when you reach Nornagol, not supposed to appear until fight is over.

Scripting needs work, Nornagol awakens and kills Crackskull before he says his lines.

Nornagol does not aggro when awakened

Nornagol's spawn appear at an extremely high rate.

Nornagol repeatedly performs his belly flop maneuver

More missing dialogue:

Gwindeth says, "I told you not to wake Nornagol!"
Gwindeth says, "I will bring the Silithar to Calenglad, for I wish to speak with him again."

**Comment by woodx319** [comment]
merged https://github.com/echoes-emu/echoes-bt/issues/926
