### ISSUE TITLE
Instance "The Blade That was Broken" needs scripting work

### ISSUE THREAD

**Issue by bcp19** [echoes-emu/echoes-bt#925]
When you enter and talk to Aragon, he runs forward to the area where everyone is waiting and then nothing happens.

Quest ID: 70009673

Aragorn

Selection: 0x031FBF500000009E (0x041FBF500000001C)
 DID: 0x700001C1
 Loc: bx251 by245 c4 ox-50.1511 oy7.6892 oz-116.044 r171 (Instance 0)
 Move table: 0x0700003B
State stack:
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

**Comment by woodx319** [comment]
merged https://github.com/echoes-emu/echoes-bt/issues/926
