### ISSUE TITLE
Target of queued skill not retained through induction

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#94]
As an LM, target your pet, queue Beacon of Hope, target a mob, and the pet will not be healed. If the pet is kept targeted the skill will work.

**Comment by dawnz85** [comment]
Visuals are present but the heal is not applied

**Comment by dawnz85** [comment]
https://www.youtube.com/watch?v=is7V9g6v_ww

**Comment by echoes-emu** [comment]
Fixed in 3ca818a2
