### ISSUE TITLE
Quest:Warning: Evil Men

### ISSUE THREAD

**Issue by Invizet** [echoes-emu/echoes-bt#944]
!quest 70007DF2: 

The stick is inactive to use. 

![ScreenShot00037](https://user-images.githubusercontent.com/37710256/232312801-189b93af-084a-451b-8b63-17432581f01d.jpg)

**Comment by woodx319** [comment]
!goto bx180 by132 c0 ox87.159 oy55.8619 oz1233.59 r6 (Instance 0)

Unable to repro signpost at this loc is working fine and progresses quest 

https://user-images.githubusercontent.com/104697795/232979074-a53cb514-aaf1-45ab-a376-8daf1eb5167e.mp4

**Comment by woodx319** [comment]
make sure room in inventory 

![ScreenShot00035](https://user-images.githubusercontent.com/104697795/232989191-d63e1e9e-81d9-431b-950e-02be8a6e5d6b.jpg)
