### ISSUE TITLE
Quest: Real Treasure

### ISSUE THREAD

**Issue by Invizet** [echoes-emu/echoes-bt#945]
Heikki don't want to talk (inactive NPC).

Selection: 0x031F3FA0000002CB (0x041F3FA00000004B)
 DID: 0x70000081
 Loc: bx243 by250 c80 ox38.3877 oy236.374 oz-187.873 r205 (Instance 0)
 Move table: 0x070001E7
State stack:
(Interacting)
(Interacting)
(Interacting)
(Interacting)
(Interacting)
(Interacting)
(Interacting)
(Interacting)
(Idle)
Melee combat mode: combat_monster
Ranged combat mode: combat_monster

![ScreenShot00041](https://user-images.githubusercontent.com/37710256/232870777-014851c1-cef7-4a07-9886-d864372c26e8.jpg)

**Comment by woodx319** [comment]
!quest 70000082: 
!goto bx243 by250 c384 ox36.6106 oy236.004 oz-187.923 r63 (Instance 0)

I am not able to repro this one. Got the quest. Went to Heikki. He doesn't have a ring above his head. 

Are your bags full? Do you have the chest in your inventory? 
![ScreenShot00034](https://user-images.githubusercontent.com/104697795/232981061-f45f6f07-e4a4-4a27-8b29-8f222389549e.jpg)

**Comment by woodx319** [comment]
Adding notes for the quest chain: it looks like the quest cash completions clear the chests from your inventory. When you pick up 'Real Treasure' you should get a Ancient Dwarf Chest AND a Damaged Dwarf Chest

The quest will tell you to go talk to Heikki whether you have the chests or not. I would cancel and make sure you have multiple empty slots. then pick up quest again and see if you get the two chests

Real Treasure: 
giver Larus:
bx178 by124 c0 ox77.517 oy68.5219 oz893.427 r197 (Instance 0)
Damaged Dwarf Chest: 
bx177 by128 c0 ox155.342 oy58.001 oz1053.42 r184 (Instance 0)

Every last ingot
giver: same

The other chest
giver:
same
Obj:
 bx183 by120 c0 ox119.568 oy21.4947 oz948.284 r104 (Instance 0)

the last ingot:
Giver: bx183 by120 c0 ox119.568 oy21.4947 oz948.284 r104 (Instance 0)]
obj;
bx185 by117 c0 ox34.5622 oy98.1945 oz1001.17 r86 (Instance 0)

**Comment by woodx319** [comment]
This quest was completable so closing as no issues with completing. However, it is another 'overflow' example so linking with the other ticket :)
