### ISSUE TITLE
A daring rescue

### ISSUE THREAD

**Issue by sluwe-vos** [echoes-emu/echoes-bt#946]
A daring rescue:
location of quest npc: You are at: bx135 by111 c0 ox96.8532 oy71.8686 oz472.782 r10 (Instance 0)
location of bug: You are at: bx135 by110 c0 ox22.8941 oy26.3159 oz467.686 r0 (Instance 0)

picture 1: she falls through the stairs on the left ! WHEN RUNNING UP THE STAIRS ! and gets stuck on the right.
![image](https://user-images.githubusercontent.com/15167869/233419411-c516c30b-9fc8-4250-8885-1c128f148d5a.png)
picture 2: the fix is rather easy if goblins when aggroed can walk through the gate in the center. If not they run from the edge where the player is standing and will have the NPC follow them.
![image](https://user-images.githubusercontent.com/15167869/233419688-2983f1cc-d31c-4693-939f-fd44c394d177.png)

I was able to reproduce this bug three times in sequence

**Comment by woodx319** [comment]
This tricksy one again. Merging
