### ISSUE TITLE
Lore-master pet skills disappearing

### ISSUE THREAD

**Issue by multipunches** [echoes-emu/echoes-bt#98]
Occasionally pet skills disappear and come back.

![image](https://user-images.githubusercontent.com/14816951/153543665-17aa6799-f70a-40e7-9fa8-68d0d24e1bd8.png)

Dismissed, recalled

![image](https://user-images.githubusercontent.com/14816951/153543706-2c396070-83b9-4abb-ad03-b67ebdbe690c.png)

**Comment by echoes-emu** [comment]
Fixed in 765acc93
